
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Ref. structure for BAPI parameter ExtensionIn/ExtensionOut
  /// </summary>
  [RfcStructure(AbapName ="BAPIPAREX" , Length = 990, Length2 = 1980)]
  [Serializable]
  public class BAPIPAREX : SAPStructure
  {
   

    /// <summary>
    /// Structure name of  BAPI table extension
    /// </summary>
 
    [RfcField(AbapName = "STRUCTURE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 0, Offset2 = 0)]
    [XmlElement("STRUCTURE", Form=XmlSchemaForm.Unqualified)]
    public string Structure0
    { 
       get
       {
          return _Structure0;
       }
       set
       {
          _Structure0 = value;
       }
    }
    private string _Structure0;


    /// <summary>
    /// Data part of BAPI extension parameter
    /// </summary>
 
    [RfcField(AbapName = "VALUEPART1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 240, Length2 = 480, Offset = 30, Offset2 = 60)]
    [XmlElement("VALUEPART1", Form=XmlSchemaForm.Unqualified)]
    public string Valuepart1
    { 
       get
       {
          return _Valuepart1;
       }
       set
       {
          _Valuepart1 = value;
       }
    }
    private string _Valuepart1;


    /// <summary>
    /// Data part of BAPI extension parameter
    /// </summary>
 
    [RfcField(AbapName = "VALUEPART2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 240, Length2 = 480, Offset = 270, Offset2 = 540)]
    [XmlElement("VALUEPART2", Form=XmlSchemaForm.Unqualified)]
    public string Valuepart2
    { 
       get
       {
          return _Valuepart2;
       }
       set
       {
          _Valuepart2 = value;
       }
    }
    private string _Valuepart2;


    /// <summary>
    /// Data part of BAPI extension parameter
    /// </summary>
 
    [RfcField(AbapName = "VALUEPART3", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 240, Length2 = 480, Offset = 510, Offset2 = 1020)]
    [XmlElement("VALUEPART3", Form=XmlSchemaForm.Unqualified)]
    public string Valuepart3
    { 
       get
       {
          return _Valuepart3;
       }
       set
       {
          _Valuepart3 = value;
       }
    }
    private string _Valuepart3;


    /// <summary>
    /// Data part of BAPI extension parameter
    /// </summary>
 
    [RfcField(AbapName = "VALUEPART4", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 240, Length2 = 480, Offset = 750, Offset2 = 1500)]
    [XmlElement("VALUEPART4", Form=XmlSchemaForm.Unqualified)]
    public string Valuepart4
    { 
       get
       {
          return _Valuepart4;
       }
       set
       {
          _Valuepart4 = value;
       }
    }
    private string _Valuepart4;

  }

}
