
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI Structure for Activity Elements (Export)
  /// </summary>
  [RfcStructure(AbapName ="BAPI_ACT_ELEMENT_EXP" , Length = 630, Length2 = 1176)]
  [Serializable]
  public class BAPI_ACT_ELEMENT_EXP : SAPStructure
  {
   

    /// <summary>
    /// Network number
    /// </summary>
 
    [RfcField(AbapName = "NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 0, Offset2 = 0)]
    [XmlElement("NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Network
    { 
       get
       {
          return _Network;
       }
       set
       {
          _Network = value;
       }
    }
    private string _Network;


    /// <summary>
    /// Activity number in network and standard network
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 12, Offset2 = 24)]
    [XmlElement("ACTIVITY", Form=XmlSchemaForm.Unqualified)]
    public string Activity
    { 
       get
       {
          return _Activity;
       }
       set
       {
          _Activity = value;
       }
    }
    private string _Activity;


    /// <summary>
    /// Activity element number (work/external/general costs)
    /// </summary>
 
    [RfcField(AbapName = "ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 16, Offset2 = 32)]
    [XmlElement("ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Element
    { 
       get
       {
          return _Element;
       }
       set
       {
          _Element = value;
       }
    }
    private string _Element;


    /// <summary>
    /// Control key
    /// </summary>
 
    [RfcField(AbapName = "CONTROL_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 20, Offset2 = 40)]
    [XmlElement("CONTROL_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Control_Key
    { 
       get
       {
          return _Control_Key;
       }
       set
       {
          _Control_Key = value;
       }
    }
    private string _Control_Key;


    /// <summary>
    /// Work center
    /// </summary>
 
    [RfcField(AbapName = "WORK_CNTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 8, Length2 = 16, Offset = 24, Offset2 = 48)]
    [XmlElement("WORK_CNTR", Form=XmlSchemaForm.Unqualified)]
    public string Work_Cntr
    { 
       get
       {
          return _Work_Cntr;
       }
       set
       {
          _Work_Cntr = value;
       }
    }
    private string _Work_Cntr;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 32, Offset2 = 64)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Operation short text
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 36, Offset2 = 72)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;


    /// <summary>
    /// Account Number of Vendor or Creditor
    /// </summary>
 
    [RfcField(AbapName = "VENDOR_NO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 76, Offset2 = 152)]
    [XmlElement("VENDOR_NO", Form=XmlSchemaForm.Unqualified)]
    public string Vendor_No
    { 
       get
       {
          return _Vendor_No;
       }
       set
       {
          _Vendor_No = value;
       }
    }
    private string _Vendor_No;


    /// <summary>
    /// Price
    /// </summary>
 
    [RfcField(AbapName = "PRICE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Length2 = 6, Decimals = 2, Offset = 86, Offset2 = 172)]
    [XmlElement("PRICE", Form=XmlSchemaForm.Unqualified)]
    public Decimal Price
    { 
       get
       {
          return _Price;
       }
       set
       {
          _Price = value;
       }
    }
    private Decimal _Price;


    /// <summary>
    /// Price Unit
    /// </summary>
 
    [RfcField(AbapName = "PRICE_UNIT", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Offset = 92, Offset2 = 178)]
    [XmlElement("PRICE_UNIT", Form=XmlSchemaForm.Unqualified)]
    public Decimal Price_Unit
    { 
       get
       {
          return _Price_Unit;
       }
       set
       {
          _Price_Unit = value;
       }
    }
    private Decimal _Price_Unit;


    /// <summary>
    /// Cost Element
    /// </summary>
 
    [RfcField(AbapName = "COST_ELEM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 95, Offset2 = 182)]
    [XmlElement("COST_ELEM", Form=XmlSchemaForm.Unqualified)]
    public string Cost_Elem
    { 
       get
       {
          return _Cost_Elem;
       }
       set
       {
          _Cost_Elem = value;
       }
    }
    private string _Cost_Elem;


    /// <summary>
    /// Currency Key
    /// </summary>
 
    [RfcField(AbapName = "CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 105, Offset2 = 202)]
    [XmlElement("CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Currency
    { 
       get
       {
          return _Currency;
       }
       set
       {
          _Currency = value;
       }
    }
    private string _Currency;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "CURRENCY_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 110, Offset2 = 212)]
    [XmlElement("CURRENCY_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Currency_Iso
    { 
       get
       {
          return _Currency_Iso;
       }
       set
       {
          _Currency_Iso = value;
       }
    }
    private string _Currency_Iso;


    /// <summary>
    /// Number of Purchasing Info Record
    /// </summary>
 
    [RfcField(AbapName = "INFO_REC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 113, Offset2 = 218)]
    [XmlElement("INFO_REC", Form=XmlSchemaForm.Unqualified)]
    public string Info_Rec
    { 
       get
       {
          return _Info_Rec;
       }
       set
       {
          _Info_Rec = value;
       }
    }
    private string _Info_Rec;


    /// <summary>
    /// Purchasing Organization
    /// </summary>
 
    [RfcField(AbapName = "PURCH_ORG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 123, Offset2 = 238)]
    [XmlElement("PURCH_ORG", Form=XmlSchemaForm.Unqualified)]
    public string Purch_Org
    { 
       get
       {
          return _Purch_Org;
       }
       set
       {
          _Purch_Org = value;
       }
    }
    private string _Purch_Org;


    /// <summary>
    /// Purchasing Group
    /// </summary>
 
    [RfcField(AbapName = "PUR_GROUP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 127, Offset2 = 246)]
    [XmlElement("PUR_GROUP", Form=XmlSchemaForm.Unqualified)]
    public string Pur_Group
    { 
       get
       {
          return _Pur_Group;
       }
       set
       {
          _Pur_Group = value;
       }
    }
    private string _Pur_Group;


    /// <summary>
    /// Material Group
    /// </summary>
 
    [RfcField(AbapName = "MATL_GROUP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 9, Length2 = 18, Offset = 130, Offset2 = 252)]
    [XmlElement("MATL_GROUP", Form=XmlSchemaForm.Unqualified)]
    public string Matl_Group
    { 
       get
       {
          return _Matl_Group;
       }
       set
       {
          _Matl_Group = value;
       }
    }
    private string _Matl_Group;


    /// <summary>
    /// Number of capacities required
    /// </summary>
 
    [RfcField(AbapName = "NUMBER_OF_CAPACITIES", RfcType = RFCTYPE.RFCTYPE_INT1, Length = 1, Length2 = 1, Offset = 139, Offset2 = 270)]
    [XmlElement("NUMBER_OF_CAPACITIES", Form=XmlSchemaForm.Unqualified)]
    public byte Number_Of_Capacities
    { 
       get
       {
          return _Number_Of_Capacities;
       }
       set
       {
          _Number_Of_Capacities = value;
       }
    }
    private byte _Number_Of_Capacities;


    /// <summary>
    /// Work percentage
    /// </summary>
 
    [RfcField(AbapName = "PERCENT_OF_WORK", RfcType = RFCTYPE.RFCTYPE_INT1, Length = 1, Length2 = 1, Offset = 140, Offset2 = 271)]
    [XmlElement("PERCENT_OF_WORK", Form=XmlSchemaForm.Unqualified)]
    public byte Percent_Of_Work
    { 
       get
       {
          return _Percent_Of_Work;
       }
       set
       {
          _Percent_Of_Work = value;
       }
    }
    private byte _Percent_Of_Work;


    /// <summary>
    /// Activity Type
    /// </summary>
 
    [RfcField(AbapName = "ACTTYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 141, Offset2 = 272)]
    [XmlElement("ACTTYPE", Form=XmlSchemaForm.Unqualified)]
    public string Acttype
    { 
       get
       {
          return _Acttype;
       }
       set
       {
          _Acttype = value;
       }
    }
    private string _Acttype;


    /// <summary>
    /// Costs in the activity
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_COSTS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Length2 = 6, Decimals = 2, Offset = 147, Offset2 = 284)]
    [XmlElement("ACTIVITY_COSTS", Form=XmlSchemaForm.Unqualified)]
    public Decimal Activity_Costs
    { 
       get
       {
          return _Activity_Costs;
       }
       set
       {
          _Activity_Costs = value;
       }
    }
    private Decimal _Activity_Costs;


    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 153, Offset2 = 290)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "WBS_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 177, Offset2 = 338)]
    [XmlElement("WBS_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Element
    { 
       get
       {
          return _Wbs_Element;
       }
       set
       {
          _Wbs_Element = value;
       }
    }
    private string _Wbs_Element;


    /// <summary>
    /// Distr.cap.reqmts (plant maint.,process order, network)
    /// </summary>
 
    [RfcField(AbapName = "DISTRIBUTING_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 8, Length2 = 16, Offset = 201, Offset2 = 386)]
    [XmlElement("DISTRIBUTING_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Distributing_Key
    { 
       get
       {
          return _Distributing_Key;
       }
       set
       {
          _Distributing_Key = value;
       }
    }
    private string _Distributing_Key;


    /// <summary>
    /// Tax Jurisdiction
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 209, Offset2 = 402)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Profit Center
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 224, Offset2 = 432)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// Ind: Reserv. not applicable to MRP;Purc. req. not created
    /// </summary>
 
    [RfcField(AbapName = "NOT_MRP_APPLICABLE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 234, Offset2 = 452)]
    [XmlElement("NOT_MRP_APPLICABLE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Mrp_Applicable
    { 
       get
       {
          return _Not_Mrp_Applicable;
       }
       set
       {
          _Not_Mrp_Applicable = value;
       }
    }
    private string _Not_Mrp_Applicable;


    /// <summary>
    /// Ind.: Take Activity Into Account for Project Summarization
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_SUMMARIZATION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 235, Offset2 = 454)]
    [XmlElement("PROJECT_SUMMARIZATION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Summarization
    { 
       get
       {
          return _Project_Summarization;
       }
       set
       {
          _Project_Summarization = value;
       }
    }
    private string _Project_Summarization;


    /// <summary>
    /// Unit of Measure for Activity/Operation
    /// </summary>
 
    [RfcField(AbapName = "OPERATION_MEASURE_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 236, Offset2 = 456)]
    [XmlElement("OPERATION_MEASURE_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Operation_Measure_Unit
    { 
       get
       {
          return _Operation_Measure_Unit;
       }
       set
       {
          _Operation_Measure_Unit = value;
       }
    }
    private string _Operation_Measure_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "OPERATION_MEASURE_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 239, Offset2 = 462)]
    [XmlElement("OPERATION_MEASURE_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Operation_Measure_Unit_Iso
    { 
       get
       {
          return _Operation_Measure_Unit_Iso;
       }
       set
       {
          _Operation_Measure_Unit_Iso = value;
       }
    }
    private string _Operation_Measure_Unit_Iso;


    /// <summary>
    /// Planned Delivery Time in Days
    /// </summary>
 
    [RfcField(AbapName = "PLND_DELRY", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 2, Length2 = 2, Offset = 242, Offset2 = 468)]
    [XmlElement("PLND_DELRY", Form=XmlSchemaForm.Unqualified)]
    public Decimal Plnd_Delry
    { 
       get
       {
          return _Plnd_Delry;
       }
       set
       {
          _Plnd_Delry = value;
       }
    }
    private Decimal _Plnd_Delry;


    /// <summary>
    /// Work involved in the activity
    /// </summary>
 
    [RfcField(AbapName = "WORK_ACTIVITY", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 4, Length2 = 4, Decimals = 1, Offset = 244, Offset2 = 470)]
    [XmlElement("WORK_ACTIVITY", Form=XmlSchemaForm.Unqualified)]
    public Decimal Work_Activity
    { 
       get
       {
          return _Work_Activity;
       }
       set
       {
          _Work_Activity = value;
       }
    }
    private Decimal _Work_Activity;


    /// <summary>
    /// Unit for work
    /// </summary>
 
    [RfcField(AbapName = "UN_WORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 248, Offset2 = 474)]
    [XmlElement("UN_WORK", Form=XmlSchemaForm.Unqualified)]
    public string Un_Work
    { 
       get
       {
          return _Un_Work;
       }
       set
       {
          _Un_Work = value;
       }
    }
    private string _Un_Work;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "UN_WORK_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 251, Offset2 = 480)]
    [XmlElement("UN_WORK_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Un_Work_Iso
    { 
       get
       {
          return _Un_Work_Iso;
       }
       set
       {
          _Un_Work_Iso = value;
       }
    }
    private string _Un_Work_Iso;


    /// <summary>
    /// Earliest scheduled start: Execution (date)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 254, Offset2 = 486)]
    [XmlElement("EARLY_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Date
    { 
       get
       {
          return _Early_Start_Date;
       }
       set
       {
          _Early_Start_Date = value;
       }
    }
    private string _Early_Start_Date;


    /// <summary>
    /// Earliest scheduled start: Execution (time)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_TIME", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 262, Offset2 = 502)]
    [XmlElement("EARLY_START_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Time
    { 
       get
       {
          return _Early_Start_Time;
       }
       set
       {
          _Early_Start_Time = value;
       }
    }
    private string _Early_Start_Time;


    /// <summary>
    /// Earliest scheduled finish: Execution (date)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 268, Offset2 = 514)]
    [XmlElement("EARLY_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Date
    { 
       get
       {
          return _Early_Finish_Date;
       }
       set
       {
          _Early_Finish_Date = value;
       }
    }
    private string _Early_Finish_Date;


    /// <summary>
    /// Earliest scheduled finish: Execution (time)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_TIME", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 276, Offset2 = 530)]
    [XmlElement("EARLY_FINISH_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Time
    { 
       get
       {
          return _Early_Finish_Time;
       }
       set
       {
          _Early_Finish_Time = value;
       }
    }
    private string _Early_Finish_Time;


    /// <summary>
    /// Latest scheduled start: Execution (date)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 282, Offset2 = 542)]
    [XmlElement("LATEST_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Date
    { 
       get
       {
          return _Latest_Start_Date;
       }
       set
       {
          _Latest_Start_Date = value;
       }
    }
    private string _Latest_Start_Date;


    /// <summary>
    /// Latest scheduled start: Execution (time)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_TIME", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 290, Offset2 = 558)]
    [XmlElement("LATEST_START_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Time
    { 
       get
       {
          return _Latest_Start_Time;
       }
       set
       {
          _Latest_Start_Time = value;
       }
    }
    private string _Latest_Start_Time;


    /// <summary>
    /// Latest scheduled finish: Execution (date)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 296, Offset2 = 570)]
    [XmlElement("LATEST_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Date
    { 
       get
       {
          return _Latest_Finish_Date;
       }
       set
       {
          _Latest_Finish_Date = value;
       }
    }
    private string _Latest_Finish_Date;


    /// <summary>
    /// Latest scheduled finish: Execution (time)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_TIME", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 304, Offset2 = 586)]
    [XmlElement("LATEST_FINISH_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Time
    { 
       get
       {
          return _Latest_Finish_Time;
       }
       set
       {
          _Latest_Finish_Time = value;
       }
    }
    private string _Latest_Finish_Time;


    /// <summary>
    /// Key word ID for user-defined fields
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 310, Offset2 = 598)]
    [XmlElement("USER_FIELD_KEY", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Key
    { 
       get
       {
          return _User_Field_Key;
       }
       set
       {
          _User_Field_Key = value;
       }
    }
    private string _User_Field_Key;


    /// <summary>
    /// User field with 20 characters
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR20_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 317, Offset2 = 612)]
    [XmlElement("USER_FIELD_CHAR20_1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char20_1
    { 
       get
       {
          return _User_Field_Char20_1;
       }
       set
       {
          _User_Field_Char20_1 = value;
       }
    }
    private string _User_Field_Char20_1;


    /// <summary>
    /// User field with 20 characters
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR20_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 337, Offset2 = 652)]
    [XmlElement("USER_FIELD_CHAR20_2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char20_2
    { 
       get
       {
          return _User_Field_Char20_2;
       }
       set
       {
          _User_Field_Char20_2 = value;
       }
    }
    private string _User_Field_Char20_2;


    /// <summary>
    /// User field with 10 characters
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR10_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 357, Offset2 = 692)]
    [XmlElement("USER_FIELD_CHAR10_1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char10_1
    { 
       get
       {
          return _User_Field_Char10_1;
       }
       set
       {
          _User_Field_Char10_1 = value;
       }
    }
    private string _User_Field_Char10_1;


    /// <summary>
    /// User field with 10 characters
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR10_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 367, Offset2 = 712)]
    [XmlElement("USER_FIELD_CHAR10_2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char10_2
    { 
       get
       {
          return _User_Field_Char10_2;
       }
       set
       {
          _User_Field_Char10_2 = value;
       }
    }
    private string _User_Field_Char10_2;


    /// <summary>
    /// User field for quantity (length 10.3)
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_QUAN1", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 377, Offset2 = 732)]
    [XmlElement("USER_FIELD_QUAN1", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Quan1
    { 
       get
       {
          return _User_Field_Quan1;
       }
       set
       {
          _User_Field_Quan1 = value;
       }
    }
    private Decimal _User_Field_Quan1;


    /// <summary>
    /// User field: Unit for quantity fields
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 384, Offset2 = 740)]
    [XmlElement("USER_FIELD_UNIT1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit1
    { 
       get
       {
          return _User_Field_Unit1;
       }
       set
       {
          _User_Field_Unit1 = value;
       }
    }
    private string _User_Field_Unit1;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT1_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 387, Offset2 = 746)]
    [XmlElement("USER_FIELD_UNIT1_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit1_Iso
    { 
       get
       {
          return _User_Field_Unit1_Iso;
       }
       set
       {
          _User_Field_Unit1_Iso = value;
       }
    }
    private string _User_Field_Unit1_Iso;


    /// <summary>
    /// User field for quantity (length 10.3)
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_QUAN2", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 390, Offset2 = 752)]
    [XmlElement("USER_FIELD_QUAN2", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Quan2
    { 
       get
       {
          return _User_Field_Quan2;
       }
       set
       {
          _User_Field_Quan2 = value;
       }
    }
    private Decimal _User_Field_Quan2;


    /// <summary>
    /// User field: Unit for quantity fields
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 397, Offset2 = 760)]
    [XmlElement("USER_FIELD_UNIT2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit2
    { 
       get
       {
          return _User_Field_Unit2;
       }
       set
       {
          _User_Field_Unit2 = value;
       }
    }
    private string _User_Field_Unit2;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT2_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 400, Offset2 = 766)]
    [XmlElement("USER_FIELD_UNIT2_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit2_Iso
    { 
       get
       {
          return _User_Field_Unit2_Iso;
       }
       set
       {
          _User_Field_Unit2_Iso = value;
       }
    }
    private string _User_Field_Unit2_Iso;


    /// <summary>
    /// User-defined field for values (length 10,3)
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CURR1", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 403, Offset2 = 772)]
    [XmlElement("USER_FIELD_CURR1", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Curr1
    { 
       get
       {
          return _User_Field_Curr1;
       }
       set
       {
          _User_Field_Curr1 = value;
       }
    }
    private Decimal _User_Field_Curr1;


    /// <summary>
    /// User field: Unit for value fields
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 410, Offset2 = 780)]
    [XmlElement("USER_FIELD_CUKY1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky1
    { 
       get
       {
          return _User_Field_Cuky1;
       }
       set
       {
          _User_Field_Cuky1 = value;
       }
    }
    private string _User_Field_Cuky1;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY1_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 415, Offset2 = 790)]
    [XmlElement("USER_FIELD_CUKY1_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky1_Iso
    { 
       get
       {
          return _User_Field_Cuky1_Iso;
       }
       set
       {
          _User_Field_Cuky1_Iso = value;
       }
    }
    private string _User_Field_Cuky1_Iso;


    /// <summary>
    /// User-defined field for values (length 10,3)
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CURR2", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 418, Offset2 = 796)]
    [XmlElement("USER_FIELD_CURR2", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Curr2
    { 
       get
       {
          return _User_Field_Curr2;
       }
       set
       {
          _User_Field_Curr2 = value;
       }
    }
    private Decimal _User_Field_Curr2;


    /// <summary>
    /// User field: Unit for value fields
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 425, Offset2 = 804)]
    [XmlElement("USER_FIELD_CUKY2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky2
    { 
       get
       {
          return _User_Field_Cuky2;
       }
       set
       {
          _User_Field_Cuky2 = value;
       }
    }
    private string _User_Field_Cuky2;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY2_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 430, Offset2 = 814)]
    [XmlElement("USER_FIELD_CUKY2_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky2_Iso
    { 
       get
       {
          return _User_Field_Cuky2_Iso;
       }
       set
       {
          _User_Field_Cuky2_Iso = value;
       }
    }
    private string _User_Field_Cuky2_Iso;


    /// <summary>
    /// User field for date
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_DATE1", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 433, Offset2 = 820)]
    [XmlElement("USER_FIELD_DATE1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Date1
    { 
       get
       {
          return _User_Field_Date1;
       }
       set
       {
          _User_Field_Date1 = value;
       }
    }
    private string _User_Field_Date1;


    /// <summary>
    /// User field for date
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_DATE2", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 441, Offset2 = 836)]
    [XmlElement("USER_FIELD_DATE2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Date2
    { 
       get
       {
          return _User_Field_Date2;
       }
       set
       {
          _User_Field_Date2 = value;
       }
    }
    private string _User_Field_Date2;


    /// <summary>
    /// User-defined field: Indicator for reports
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_FLAG1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 449, Offset2 = 852)]
    [XmlElement("USER_FIELD_FLAG1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Flag1
    { 
       get
       {
          return _User_Field_Flag1;
       }
       set
       {
          _User_Field_Flag1 = value;
       }
    }
    private string _User_Field_Flag1;


    /// <summary>
    /// User-defined field: Indicator for reports
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_FLAG2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 450, Offset2 = 854)]
    [XmlElement("USER_FIELD_FLAG2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Flag2
    { 
       get
       {
          return _User_Field_Flag2;
       }
       set
       {
          _User_Field_Flag2 = value;
       }
    }
    private string _User_Field_Flag2;


    /// <summary>
    /// Deletion Indicator
    /// </summary>
 
    [RfcField(AbapName = "DELETION_FLAG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 451, Offset2 = 856)]
    [XmlElement("DELETION_FLAG", Form=XmlSchemaForm.Unqualified)]
    public string Deletion_Flag
    { 
       get
       {
          return _Deletion_Flag;
       }
       set
       {
          _Deletion_Flag = value;
       }
    }
    private string _Deletion_Flag;


    /// <summary>
    /// Earliest scheduled start date (forecast)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_DATE_FC", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 452, Offset2 = 858)]
    [XmlElement("EARLY_START_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Date_Fc
    { 
       get
       {
          return _Early_Start_Date_Fc;
       }
       set
       {
          _Early_Start_Date_Fc = value;
       }
    }
    private string _Early_Start_Date_Fc;


    /// <summary>
    /// Earliest scheduled start time (forecast)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_TIME_FC", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 460, Offset2 = 874)]
    [XmlElement("EARLY_START_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Time_Fc
    { 
       get
       {
          return _Early_Start_Time_Fc;
       }
       set
       {
          _Early_Start_Time_Fc = value;
       }
    }
    private string _Early_Start_Time_Fc;


    /// <summary>
    /// Earliest scheduled finish date (forecast)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_DATE_FC", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 466, Offset2 = 886)]
    [XmlElement("EARLY_FINISH_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Date_Fc
    { 
       get
       {
          return _Early_Finish_Date_Fc;
       }
       set
       {
          _Early_Finish_Date_Fc = value;
       }
    }
    private string _Early_Finish_Date_Fc;


    /// <summary>
    /// Earliest scheduled finish time (forecast)
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_TIME_FC", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 474, Offset2 = 902)]
    [XmlElement("EARLY_FINISH_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Time_Fc
    { 
       get
       {
          return _Early_Finish_Time_Fc;
       }
       set
       {
          _Early_Finish_Time_Fc = value;
       }
    }
    private string _Early_Finish_Time_Fc;


    /// <summary>
    /// Latest scheduled start date (forecast)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_DATE_FC", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 480, Offset2 = 914)]
    [XmlElement("LATEST_START_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Date_Fc
    { 
       get
       {
          return _Latest_Start_Date_Fc;
       }
       set
       {
          _Latest_Start_Date_Fc = value;
       }
    }
    private string _Latest_Start_Date_Fc;


    /// <summary>
    /// Latest scheduled start time (forecast)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_TIME_FC", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 488, Offset2 = 930)]
    [XmlElement("LATEST_START_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Time_Fc
    { 
       get
       {
          return _Latest_Start_Time_Fc;
       }
       set
       {
          _Latest_Start_Time_Fc = value;
       }
    }
    private string _Latest_Start_Time_Fc;


    /// <summary>
    /// Latest scheduled finish date (forecast)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_DATE_FC", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 494, Offset2 = 942)]
    [XmlElement("LATEST_FINISH_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Date_Fc
    { 
       get
       {
          return _Latest_Finish_Date_Fc;
       }
       set
       {
          _Latest_Finish_Date_Fc = value;
       }
    }
    private string _Latest_Finish_Date_Fc;


    /// <summary>
    /// Latest scheduled finish time (forecast)
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_TIME_FC", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Length2 = 12, Offset = 502, Offset2 = 958)]
    [XmlElement("LATEST_FINISH_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Time_Fc
    { 
       get
       {
          return _Latest_Finish_Time_Fc;
       }
       set
       {
          _Latest_Finish_Time_Fc = value;
       }
    }
    private string _Latest_Finish_Time_Fc;


    /// <summary>
    /// Forecasted work (actual + remaining)
    /// </summary>
 
    [RfcField(AbapName = "WORK_FORECAST", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 4, Length2 = 4, Decimals = 1, Offset = 508, Offset2 = 970)]
    [XmlElement("WORK_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public Decimal Work_Forecast
    { 
       get
       {
          return _Work_Forecast;
       }
       set
       {
          _Work_Forecast = value;
       }
    }
    private Decimal _Work_Forecast;


    /// <summary>
    /// Actual work
    /// </summary>
 
    [RfcField(AbapName = "WORK_ACTUAL", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 512, Offset2 = 974)]
    [XmlElement("WORK_ACTUAL", Form=XmlSchemaForm.Unqualified)]
    public Decimal Work_Actual
    { 
       get
       {
          return _Work_Actual;
       }
       set
       {
          _Work_Actual = value;
       }
    }
    private Decimal _Work_Actual;


    /// <summary>
    /// Processing time
    /// </summary>
 
    [RfcField(AbapName = "DURATION_SCHEDULED", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 4, Length2 = 4, Decimals = 1, Offset = 519, Offset2 = 981)]
    [XmlElement("DURATION_SCHEDULED", Form=XmlSchemaForm.Unqualified)]
    public Decimal Duration_Scheduled
    { 
       get
       {
          return _Duration_Scheduled;
       }
       set
       {
          _Duration_Scheduled = value;
       }
    }
    private Decimal _Duration_Scheduled;


    /// <summary>
    /// Duration of processing time (forecast)
    /// </summary>
 
    [RfcField(AbapName = "DURATION_SCHEDULED_FC", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 4, Length2 = 4, Decimals = 1, Offset = 523, Offset2 = 985)]
    [XmlElement("DURATION_SCHEDULED_FC", Form=XmlSchemaForm.Unqualified)]
    public Decimal Duration_Scheduled_Fc
    { 
       get
       {
          return _Duration_Scheduled_Fc;
       }
       set
       {
          _Duration_Scheduled_Fc = value;
       }
    }
    private Decimal _Duration_Scheduled_Fc;


    /// <summary>
    /// Unit of measure for processing time
    /// </summary>
 
    [RfcField(AbapName = "DURATION_SCHEDULED_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 527, Offset2 = 990)]
    [XmlElement("DURATION_SCHEDULED_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Scheduled_Unit
    { 
       get
       {
          return _Duration_Scheduled_Unit;
       }
       set
       {
          _Duration_Scheduled_Unit = value;
       }
    }
    private string _Duration_Scheduled_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "DURATION_SCHEDULED_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 530, Offset2 = 996)]
    [XmlElement("DURATION_SCHEDULED_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Scheduled_Unit_Iso
    { 
       get
       {
          return _Duration_Scheduled_Unit_Iso;
       }
       set
       {
          _Duration_Scheduled_Unit_Iso = value;
       }
    }
    private string _Duration_Scheduled_Unit_Iso;


    /// <summary>
    /// Object class, language-dependent
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 533, Offset2 = 1002)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Offset to start of production resource/tool usage
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_START", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Offset = 538, Offset2 = 1012)]
    [XmlElement("OFFSET_START", Form=XmlSchemaForm.Unqualified)]
    public Decimal Offset_Start
    { 
       get
       {
          return _Offset_Start;
       }
       set
       {
          _Offset_Start = value;
       }
    }
    private Decimal _Offset_Start;


    /// <summary>
    /// Unit for offset to start
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_START_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 541, Offset2 = 1016)]
    [XmlElement("OFFSET_START_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Start_Unit
    { 
       get
       {
          return _Offset_Start_Unit;
       }
       set
       {
          _Offset_Start_Unit = value;
       }
    }
    private string _Offset_Start_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_START_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 544, Offset2 = 1022)]
    [XmlElement("OFFSET_START_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Start_Unit_Iso
    { 
       get
       {
          return _Offset_Start_Unit_Iso;
       }
       set
       {
          _Offset_Start_Unit_Iso = value;
       }
    }
    private string _Offset_Start_Unit_Iso;


    /// <summary>
    /// Offset to sub-operation finish
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_END", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Offset = 547, Offset2 = 1028)]
    [XmlElement("OFFSET_END", Form=XmlSchemaForm.Unqualified)]
    public Decimal Offset_End
    { 
       get
       {
          return _Offset_End;
       }
       set
       {
          _Offset_End = value;
       }
    }
    private Decimal _Offset_End;


    /// <summary>
    /// Unit for offset to finish
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_END_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 550, Offset2 = 1032)]
    [XmlElement("OFFSET_END_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Offset_End_Unit
    { 
       get
       {
          return _Offset_End_Unit;
       }
       set
       {
          _Offset_End_Unit = value;
       }
    }
    private string _Offset_End_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_END_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 553, Offset2 = 1038)]
    [XmlElement("OFFSET_END_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Offset_End_Unit_Iso
    { 
       get
       {
          return _Offset_End_Unit_Iso;
       }
       set
       {
          _Offset_End_Unit_Iso = value;
       }
    }
    private string _Offset_End_Unit_Iso;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 556, Offset2 = 1044)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 560, Offset2 = 1052)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;


    /// <summary>
    /// Personnel number
    /// </summary>
 
    [RfcField(AbapName = "PERS_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 576, Offset2 = 1084)]
    [XmlElement("PERS_NO", Form=XmlSchemaForm.Unqualified)]
    public string Pers_No
    { 
       get
       {
          return _Pers_No;
       }
       set
       {
          _Pers_No = value;
       }
    }
    private string _Pers_No;


    /// <summary>
    /// Planned Costs
    /// </summary>
 
    [RfcField(AbapName = "PLANNED_COST", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 2, Offset = 584, Offset2 = 1100)]
    [XmlElement("PLANNED_COST", Form=XmlSchemaForm.Unqualified)]
    public Decimal Planned_Cost
    { 
       get
       {
          return _Planned_Cost;
       }
       set
       {
          _Planned_Cost = value;
       }
    }
    private Decimal _Planned_Cost;


    /// <summary>
    /// Actual Costs
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_COST", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 2, Offset = 592, Offset2 = 1108)]
    [XmlElement("ACTUAL_COST", Form=XmlSchemaForm.Unqualified)]
    public Decimal Actual_Cost
    { 
       get
       {
          return _Actual_Cost;
       }
       set
       {
          _Actual_Cost = value;
       }
    }
    private Decimal _Actual_Cost;


    /// <summary>
    /// Currency Key
    /// </summary>
 
    [RfcField(AbapName = "CONTROLLING_AREA_CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 600, Offset2 = 1116)]
    [XmlElement("CONTROLLING_AREA_CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Controlling_Area_Currency
    { 
       get
       {
          return _Controlling_Area_Currency;
       }
       set
       {
          _Controlling_Area_Currency = value;
       }
    }
    private string _Controlling_Area_Currency;


    /// <summary>
    /// Actual start: Execution (date)
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 605, Offset2 = 1126)]
    [XmlElement("ACTUAL_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Actual_Start_Date
    { 
       get
       {
          return _Actual_Start_Date;
       }
       set
       {
          _Actual_Start_Date = value;
       }
    }
    private string _Actual_Start_Date;


    /// <summary>
    /// Actual finish: Execution (date)
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 613, Offset2 = 1142)]
    [XmlElement("ACTUAL_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Actual_Finish_Date
    { 
       get
       {
          return _Actual_Finish_Date;
       }
       set
       {
          _Actual_Finish_Date = value;
       }
    }
    private string _Actual_Finish_Date;


    /// <summary>
    /// Forecasted confirmed finish date
    /// </summary>
 
    [RfcField(AbapName = "FORECAST_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 621, Offset2 = 1158)]
    [XmlElement("FORECAST_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Forecast_Finish_Date
    { 
       get
       {
          return _Forecast_Finish_Date;
       }
       set
       {
          _Forecast_Finish_Date = value;
       }
    }
    private string _Forecast_Finish_Date;


    /// <summary>
    /// Activate final confirmation
    /// </summary>
 
    [RfcField(AbapName = "COMPLETE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 629, Offset2 = 1174)]
    [XmlElement("COMPLETE", Form=XmlSchemaForm.Unqualified)]
    public string Complete
    { 
       get
       {
          return _Complete;
       }
       set
       {
          _Complete = value;
       }
    }
    private string _Complete;

  }

}
