
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI structure network (export)
  /// </summary>
  [RfcStructure(AbapName ="BAPI_NETWORK_EXP" , Length = 303, Length2 = 590)]
  [Serializable]
  public class BAPI_NETWORK_EXP : SAPStructure
  {
   

    /// <summary>
    /// Network number
    /// </summary>
 
    [RfcField(AbapName = "NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 0, Offset2 = 0)]
    [XmlElement("NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Network
    { 
       get
       {
          return _Network;
       }
       set
       {
          _Network = value;
       }
    }
    private string _Network;


    /// <summary>
    /// Network type
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 12, Offset2 = 24)]
    [XmlElement("NETWORK_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Network_Type
    { 
       get
       {
          return _Network_Type;
       }
       set
       {
          _Network_Type = value;
       }
    }
    private string _Network_Type;


    /// <summary>
    /// Description
    /// </summary>
 
    [RfcField(AbapName = "SHORT_TEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 16, Offset2 = 32)]
    [XmlElement("SHORT_TEXT", Form=XmlSchemaForm.Unqualified)]
    public string Short_Text
    { 
       get
       {
          return _Short_Text;
       }
       set
       {
          _Short_Text = value;
       }
    }
    private string _Short_Text;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 56, Offset2 = 112)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Profit Center
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 60, Offset2 = 120)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "WBS_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 70, Offset2 = 140)]
    [XmlElement("WBS_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Element
    { 
       get
       {
          return _Wbs_Element;
       }
       set
       {
          _Wbs_Element = value;
       }
    }
    private string _Wbs_Element;


    /// <summary>
    /// Tax Jurisdiction
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 94, Offset2 = 188)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Object class (language-independent)
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 109, Offset2 = 218)]
    [XmlElement("OBJECTCLASS", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass
    { 
       get
       {
          return _Objectclass;
       }
       set
       {
          _Objectclass = value;
       }
    }
    private string _Objectclass;


    /// <summary>
    /// Basic finish date
    /// </summary>
 
    [RfcField(AbapName = "FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 111, Offset2 = 222)]
    [XmlElement("FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Finish_Date
    { 
       get
       {
          return _Finish_Date;
       }
       set
       {
          _Finish_Date = value;
       }
    }
    private string _Finish_Date;


    /// <summary>
    /// Basic start date
    /// </summary>
 
    [RfcField(AbapName = "START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 119, Offset2 = 238)]
    [XmlElement("START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Start_Date
    { 
       get
       {
          return _Start_Date;
       }
       set
       {
          _Start_Date = value;
       }
    }
    private string _Start_Date;


    /// <summary>
    /// MRP controller for the order
    /// </summary>
 
    [RfcField(AbapName = "MRP_CONTROLLER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 127, Offset2 = 254)]
    [XmlElement("MRP_CONTROLLER", Form=XmlSchemaForm.Unqualified)]
    public string Mrp_Controller
    { 
       get
       {
          return _Mrp_Controller;
       }
       set
       {
          _Mrp_Controller = value;
       }
    }
    private string _Mrp_Controller;


    /// <summary>
    /// Scheduling type
    /// </summary>
 
    [RfcField(AbapName = "SCHED_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 130, Offset2 = 260)]
    [XmlElement("SCHED_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Type
    { 
       get
       {
          return _Sched_Type;
       }
       set
       {
          _Sched_Type = value;
       }
    }
    private string _Sched_Type;


    /// <summary>
    /// Order priority
    /// </summary>
 
    [RfcField(AbapName = "PRIORITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 131, Offset2 = 262)]
    [XmlElement("PRIORITY", Form=XmlSchemaForm.Unqualified)]
    public string Priority
    { 
       get
       {
          return _Priority;
       }
       set
       {
          _Priority = value;
       }
    }
    private string _Priority;


    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 132, Offset2 = 264)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// Indicator: Do not schedule automatically
    /// </summary>
 
    [RfcField(AbapName = "NOT_AUTO_SCHEDULE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 156, Offset2 = 312)]
    [XmlElement("NOT_AUTO_SCHEDULE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Auto_Schedule
    { 
       get
       {
          return _Not_Auto_Schedule;
       }
       set
       {
          _Not_Auto_Schedule = value;
       }
    }
    private string _Not_Auto_Schedule;


    /// <summary>
    /// Indicator: Do not cost automatically
    /// </summary>
 
    [RfcField(AbapName = "NOT_AUTO_COSTING", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 157, Offset2 = 314)]
    [XmlElement("NOT_AUTO_COSTING", Form=XmlSchemaForm.Unqualified)]
    public string Not_Auto_Costing
    { 
       get
       {
          return _Not_Auto_Costing;
       }
       set
       {
          _Not_Auto_Costing = value;
       }
    }
    private string _Not_Auto_Costing;


    /// <summary>
    /// Ind: Reserv. not applicable to MRP;Purc. req. not created
    /// </summary>
 
    [RfcField(AbapName = "NOT_MRP_APPLICABLE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 158, Offset2 = 316)]
    [XmlElement("NOT_MRP_APPLICABLE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Mrp_Applicable
    { 
       get
       {
          return _Not_Mrp_Applicable;
       }
       set
       {
          _Not_Mrp_Applicable = value;
       }
    }
    private string _Not_Mrp_Applicable;


    /// <summary>
    /// Network profile
    /// </summary>
 
    [RfcField(AbapName = "PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 159, Offset2 = 318)]
    [XmlElement("PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Profile
    { 
       get
       {
          return _Profile;
       }
       set
       {
          _Profile = value;
       }
    }
    private string _Profile;


    /// <summary>
    /// Deletion Indicator
    /// </summary>
 
    [RfcField(AbapName = "DELETION_FLAG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 166, Offset2 = 332)]
    [XmlElement("DELETION_FLAG", Form=XmlSchemaForm.Unqualified)]
    public string Deletion_Flag
    { 
       get
       {
          return _Deletion_Flag;
       }
       set
       {
          _Deletion_Flag = value;
       }
    }
    private string _Deletion_Flag;


    /// <summary>
    /// Object class, language-dependent
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 167, Offset2 = 334)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Scheduled start
    /// </summary>
 
    [RfcField(AbapName = "SCHED_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 172, Offset2 = 344)]
    [XmlElement("SCHED_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Start_Date
    { 
       get
       {
          return _Sched_Start_Date;
       }
       set
       {
          _Sched_Start_Date = value;
       }
    }
    private string _Sched_Start_Date;


    /// <summary>
    /// Scheduled finish
    /// </summary>
 
    [RfcField(AbapName = "SCHED_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 180, Offset2 = 360)]
    [XmlElement("SCHED_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Finish_Date
    { 
       get
       {
          return _Sched_Finish_Date;
       }
       set
       {
          _Sched_Finish_Date = value;
       }
    }
    private string _Sched_Finish_Date;


    /// <summary>
    /// Scheduled release date
    /// </summary>
 
    [RfcField(AbapName = "SCHED_RELEASE_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 188, Offset2 = 376)]
    [XmlElement("SCHED_RELEASE_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Release_Date
    { 
       get
       {
          return _Sched_Release_Date;
       }
       set
       {
          _Sched_Release_Date = value;
       }
    }
    private string _Sched_Release_Date;


    /// <summary>
    /// Scheduling type (forecast)
    /// </summary>
 
    [RfcField(AbapName = "SCHED_TYPE_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 196, Offset2 = 392)]
    [XmlElement("SCHED_TYPE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Type_Forecast
    { 
       get
       {
          return _Sched_Type_Forecast;
       }
       set
       {
          _Sched_Type_Forecast = value;
       }
    }
    private string _Sched_Type_Forecast;


    /// <summary>
    /// Forecast start date
    /// </summary>
 
    [RfcField(AbapName = "START_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 197, Offset2 = 394)]
    [XmlElement("START_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Start_Date_Forecast
    { 
       get
       {
          return _Start_Date_Forecast;
       }
       set
       {
          _Start_Date_Forecast = value;
       }
    }
    private string _Start_Date_Forecast;


    /// <summary>
    /// Finish date (forecast)
    /// </summary>
 
    [RfcField(AbapName = "FINISH_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 205, Offset2 = 410)]
    [XmlElement("FINISH_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Finish_Date_Forecast
    { 
       get
       {
          return _Finish_Date_Forecast;
       }
       set
       {
          _Finish_Date_Forecast = value;
       }
    }
    private string _Finish_Date_Forecast;


    /// <summary>
    /// Scheduled forecast start
    /// </summary>
 
    [RfcField(AbapName = "SCHED_START_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 213, Offset2 = 426)]
    [XmlElement("SCHED_START_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Start_Date_Forecast
    { 
       get
       {
          return _Sched_Start_Date_Forecast;
       }
       set
       {
          _Sched_Start_Date_Forecast = value;
       }
    }
    private string _Sched_Start_Date_Forecast;


    /// <summary>
    /// Scheduled forecast finish
    /// </summary>
 
    [RfcField(AbapName = "SCHED_FINISH_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 221, Offset2 = 442)]
    [XmlElement("SCHED_FINISH_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Finish_Date_Forecast
    { 
       get
       {
          return _Sched_Finish_Date_Forecast;
       }
       set
       {
          _Sched_Finish_Date_Forecast = value;
       }
    }
    private string _Sched_Finish_Date_Forecast;


    /// <summary>
    /// Scheduled release date (forecast)
    /// </summary>
 
    [RfcField(AbapName = "SCHED_RELEASE_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 229, Offset2 = 458)]
    [XmlElement("SCHED_RELEASE_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Release_Date_Forecast
    { 
       get
       {
          return _Sched_Release_Date_Forecast;
       }
       set
       {
          _Sched_Release_Date_Forecast = value;
       }
    }
    private string _Sched_Release_Date_Forecast;


    /// <summary>
    /// Actual start date
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 237, Offset2 = 474)]
    [XmlElement("ACTUAL_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Actual_Start_Date
    { 
       get
       {
          return _Actual_Start_Date;
       }
       set
       {
          _Actual_Start_Date = value;
       }
    }
    private string _Actual_Start_Date;


    /// <summary>
    /// Confirmed Order Finish Date
    /// </summary>
 
    [RfcField(AbapName = "CONFIRMED_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 245, Offset2 = 490)]
    [XmlElement("CONFIRMED_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Confirmed_Finish_Date
    { 
       get
       {
          return _Confirmed_Finish_Date;
       }
       set
       {
          _Confirmed_Finish_Date = value;
       }
    }
    private string _Confirmed_Finish_Date;


    /// <summary>
    /// Actual release date
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_RELEASE_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 253, Offset2 = 506)]
    [XmlElement("ACTUAL_RELEASE_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Actual_Release_Date
    { 
       get
       {
          return _Actual_Release_Date;
       }
       set
       {
          _Actual_Release_Date = value;
       }
    }
    private string _Actual_Release_Date;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 261, Offset2 = 522)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 265, Offset2 = 530)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;


    /// <summary>
    /// Planned Costs
    /// </summary>
 
    [RfcField(AbapName = "PLANNED_COST", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 2, Offset = 281, Offset2 = 562)]
    [XmlElement("PLANNED_COST", Form=XmlSchemaForm.Unqualified)]
    public Decimal Planned_Cost
    { 
       get
       {
          return _Planned_Cost;
       }
       set
       {
          _Planned_Cost = value;
       }
    }
    private Decimal _Planned_Cost;


    /// <summary>
    /// Actual Costs
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_COST", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 2, Offset = 289, Offset2 = 570)]
    [XmlElement("ACTUAL_COST", Form=XmlSchemaForm.Unqualified)]
    public Decimal Actual_Cost
    { 
       get
       {
          return _Actual_Cost;
       }
       set
       {
          _Actual_Cost = value;
       }
    }
    private Decimal _Actual_Cost;


    /// <summary>
    /// Currency Key
    /// </summary>
 
    [RfcField(AbapName = "CONTROLLING_AREA_CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 297, Offset2 = 578)]
    [XmlElement("CONTROLLING_AREA_CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Controlling_Area_Currency
    { 
       get
       {
          return _Controlling_Area_Currency;
       }
       set
       {
          _Controlling_Area_Currency = value;
       }
    }
    private string _Controlling_Area_Currency;


    /// <summary>
    /// Network: Activity-Assigned
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_ACCOUNT_ASSIGNED", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 302, Offset2 = 588)]
    [XmlElement("ACTIVITY_ACCOUNT_ASSIGNED", Form=XmlSchemaForm.Unqualified)]
    public string Activity_Account_Assigned
    { 
       get
       {
          return _Activity_Account_Assigned;
       }
       set
       {
          _Activity_Account_Assigned = value;
       }
    }
    private string _Activity_Account_Assigned;

  }

}
