
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Update structure: Network relations
  /// </summary>
  [RfcStructure(AbapName ="BAPI_NETWORK_RELATION_UP" , Length = 13, Length2 = 26)]
  [Serializable]
  public class BAPI_NETWORK_RELATION_UP : SAPStructure
  {
   

    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_PREDECESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("NETWORK_PREDECESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Network_Predecessor
    { 
       get
       {
          return _Network_Predecessor;
       }
       set
       {
          _Network_Predecessor = value;
       }
    }
    private string _Network_Predecessor;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_PREDECESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 1, Offset2 = 2)]
    [XmlElement("ACTIVITY_PREDECESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Activity_Predecessor
    { 
       get
       {
          return _Activity_Predecessor;
       }
       set
       {
          _Activity_Predecessor = value;
       }
    }
    private string _Activity_Predecessor;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_SUCCESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 2, Offset2 = 4)]
    [XmlElement("NETWORK_SUCCESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Network_Successor
    { 
       get
       {
          return _Network_Successor;
       }
       set
       {
          _Network_Successor = value;
       }
    }
    private string _Network_Successor;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_SUCCESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 3, Offset2 = 6)]
    [XmlElement("ACTIVITY_SUCCESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Activity_Successor
    { 
       get
       {
          return _Activity_Successor;
       }
       set
       {
          _Activity_Successor = value;
       }
    }
    private string _Activity_Successor;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "RELATION_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 4, Offset2 = 8)]
    [XmlElement("RELATION_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Relation_Type
    { 
       get
       {
          return _Relation_Type;
       }
       set
       {
          _Relation_Type = value;
       }
    }
    private string _Relation_Type;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DURATION_RELATION_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 5, Offset2 = 10)]
    [XmlElement("DURATION_RELATION_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Relation_Unit
    { 
       get
       {
          return _Duration_Relation_Unit;
       }
       set
       {
          _Duration_Relation_Unit = value;
       }
    }
    private string _Duration_Relation_Unit;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DURATION_RELATION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 6, Offset2 = 12)]
    [XmlElement("DURATION_RELATION", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Relation
    { 
       get
       {
          return _Duration_Relation;
       }
       set
       {
          _Duration_Relation = value;
       }
    }
    private string _Duration_Relation;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DURATION_RELATION_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 7, Offset2 = 14)]
    [XmlElement("DURATION_RELATION_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Relation_Unit_Iso
    { 
       get
       {
          return _Duration_Relation_Unit_Iso;
       }
       set
       {
          _Duration_Relation_Unit_Iso = value;
       }
    }
    private string _Duration_Relation_Unit_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FACTORY_CALENDAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 8, Offset2 = 16)]
    [XmlElement("FACTORY_CALENDAR", Form=XmlSchemaForm.Unqualified)]
    public string Factory_Calendar
    { 
       get
       {
          return _Factory_Calendar;
       }
       set
       {
          _Factory_Calendar = value;
       }
    }
    private string _Factory_Calendar;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PERCENT_OF_SUC_PR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 9, Offset2 = 18)]
    [XmlElement("PERCENT_OF_SUC_PR", Form=XmlSchemaForm.Unqualified)]
    public string Percent_Of_Suc_Pr
    { 
       get
       {
          return _Percent_Of_Suc_Pr;
       }
       set
       {
          _Percent_Of_Suc_Pr = value;
       }
    }
    private string _Percent_Of_Suc_Pr;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DURATION_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 10, Offset2 = 20)]
    [XmlElement("DURATION_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Key
    { 
       get
       {
          return _Duration_Key;
       }
       set
       {
          _Duration_Key = value;
       }
    }
    private string _Duration_Key;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "WORK_CNTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 11, Offset2 = 22)]
    [XmlElement("WORK_CNTR", Form=XmlSchemaForm.Unqualified)]
    public string Work_Cntr
    { 
       get
       {
          return _Work_Cntr;
       }
       set
       {
          _Work_Cntr = value;
       }
    }
    private string _Work_Cntr;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 12, Offset2 = 24)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;

  }

}
