
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Network BAPI structure
  /// </summary>
  [RfcStructure(AbapName ="BAPI_NETWORK" , Length = 208, Length2 = 416)]
  [Serializable]
  public class BAPI_NETWORK : SAPStructure
  {
   

    /// <summary>
    /// Network number
    /// </summary>
 
    [RfcField(AbapName = "NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 0, Offset2 = 0)]
    [XmlElement("NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Network
    { 
       get
       {
          return _Network;
       }
       set
       {
          _Network = value;
       }
    }
    private string _Network;


    /// <summary>
    /// Network type
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 12, Offset2 = 24)]
    [XmlElement("NETWORK_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Network_Type
    { 
       get
       {
          return _Network_Type;
       }
       set
       {
          _Network_Type = value;
       }
    }
    private string _Network_Type;


    /// <summary>
    /// Description
    /// </summary>
 
    [RfcField(AbapName = "SHORT_TEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 16, Offset2 = 32)]
    [XmlElement("SHORT_TEXT", Form=XmlSchemaForm.Unqualified)]
    public string Short_Text
    { 
       get
       {
          return _Short_Text;
       }
       set
       {
          _Short_Text = value;
       }
    }
    private string _Short_Text;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 56, Offset2 = 112)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Profit Center
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 60, Offset2 = 120)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "WBS_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 70, Offset2 = 140)]
    [XmlElement("WBS_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Element
    { 
       get
       {
          return _Wbs_Element;
       }
       set
       {
          _Wbs_Element = value;
       }
    }
    private string _Wbs_Element;


    /// <summary>
    /// Tax Jurisdiction
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 94, Offset2 = 188)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Object class (language-independent)
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 109, Offset2 = 218)]
    [XmlElement("OBJECTCLASS", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass
    { 
       get
       {
          return _Objectclass;
       }
       set
       {
          _Objectclass = value;
       }
    }
    private string _Objectclass;


    /// <summary>
    /// Basic finish date
    /// </summary>
 
    [RfcField(AbapName = "FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 111, Offset2 = 222)]
    [XmlElement("FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Finish_Date
    { 
       get
       {
          return _Finish_Date;
       }
       set
       {
          _Finish_Date = value;
       }
    }
    private string _Finish_Date;


    /// <summary>
    /// Basic start date
    /// </summary>
 
    [RfcField(AbapName = "START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 119, Offset2 = 238)]
    [XmlElement("START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Start_Date
    { 
       get
       {
          return _Start_Date;
       }
       set
       {
          _Start_Date = value;
       }
    }
    private string _Start_Date;


    /// <summary>
    /// MRP controller for the order
    /// </summary>
 
    [RfcField(AbapName = "MRP_CONTROLLER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 127, Offset2 = 254)]
    [XmlElement("MRP_CONTROLLER", Form=XmlSchemaForm.Unqualified)]
    public string Mrp_Controller
    { 
       get
       {
          return _Mrp_Controller;
       }
       set
       {
          _Mrp_Controller = value;
       }
    }
    private string _Mrp_Controller;


    /// <summary>
    /// Scheduling type
    /// </summary>
 
    [RfcField(AbapName = "SCHED_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 130, Offset2 = 260)]
    [XmlElement("SCHED_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Type
    { 
       get
       {
          return _Sched_Type;
       }
       set
       {
          _Sched_Type = value;
       }
    }
    private string _Sched_Type;


    /// <summary>
    /// Order priority
    /// </summary>
 
    [RfcField(AbapName = "PRIORITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 131, Offset2 = 262)]
    [XmlElement("PRIORITY", Form=XmlSchemaForm.Unqualified)]
    public string Priority
    { 
       get
       {
          return _Priority;
       }
       set
       {
          _Priority = value;
       }
    }
    private string _Priority;


    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 132, Offset2 = 264)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// Indicator: Do not schedule automatically
    /// </summary>
 
    [RfcField(AbapName = "NOT_AUTO_SCHEDULE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 156, Offset2 = 312)]
    [XmlElement("NOT_AUTO_SCHEDULE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Auto_Schedule
    { 
       get
       {
          return _Not_Auto_Schedule;
       }
       set
       {
          _Not_Auto_Schedule = value;
       }
    }
    private string _Not_Auto_Schedule;


    /// <summary>
    /// Indicator: Do not cost automatically
    /// </summary>
 
    [RfcField(AbapName = "NOT_AUTO_COSTING", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 157, Offset2 = 314)]
    [XmlElement("NOT_AUTO_COSTING", Form=XmlSchemaForm.Unqualified)]
    public string Not_Auto_Costing
    { 
       get
       {
          return _Not_Auto_Costing;
       }
       set
       {
          _Not_Auto_Costing = value;
       }
    }
    private string _Not_Auto_Costing;


    /// <summary>
    /// Ind: Reserv. not applicable to MRP;Purc. req. not created
    /// </summary>
 
    [RfcField(AbapName = "NOT_MRP_APPLICABLE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 158, Offset2 = 316)]
    [XmlElement("NOT_MRP_APPLICABLE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Mrp_Applicable
    { 
       get
       {
          return _Not_Mrp_Applicable;
       }
       set
       {
          _Not_Mrp_Applicable = value;
       }
    }
    private string _Not_Mrp_Applicable;


    /// <summary>
    /// Network profile
    /// </summary>
 
    [RfcField(AbapName = "PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 159, Offset2 = 318)]
    [XmlElement("PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Profile
    { 
       get
       {
          return _Profile;
       }
       set
       {
          _Profile = value;
       }
    }
    private string _Profile;


    /// <summary>
    /// Finish date (forecast)
    /// </summary>
 
    [RfcField(AbapName = "FINISH_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 166, Offset2 = 332)]
    [XmlElement("FINISH_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Finish_Date_Forecast
    { 
       get
       {
          return _Finish_Date_Forecast;
       }
       set
       {
          _Finish_Date_Forecast = value;
       }
    }
    private string _Finish_Date_Forecast;


    /// <summary>
    /// Forecast start date
    /// </summary>
 
    [RfcField(AbapName = "START_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 174, Offset2 = 348)]
    [XmlElement("START_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Start_Date_Forecast
    { 
       get
       {
          return _Start_Date_Forecast;
       }
       set
       {
          _Start_Date_Forecast = value;
       }
    }
    private string _Start_Date_Forecast;


    /// <summary>
    /// Scheduling type (forecast)
    /// </summary>
 
    [RfcField(AbapName = "SCHED_TYPE_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 182, Offset2 = 364)]
    [XmlElement("SCHED_TYPE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Type_Forecast
    { 
       get
       {
          return _Sched_Type_Forecast;
       }
       set
       {
          _Sched_Type_Forecast = value;
       }
    }
    private string _Sched_Type_Forecast;


    /// <summary>
    /// Object class, language-dependent
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 183, Offset2 = 366)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 188, Offset2 = 376)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 192, Offset2 = 384)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;

  }

}
