
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Data Structure: Project Definition GetData
  /// </summary>
  [RfcStructure(AbapName ="BAPI_BUS2001_DETAIL" , Length = 363, Length2 = 726)]
  [Serializable]
  public class BAPI_BUS2001_DETAIL : SAPStructure
  {
   

    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 0, Offset2 = 0)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// PS: Short description (1st text line)
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 24, Offset2 = 48)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;


    /// <summary>
    /// Selection mask for WBS element short IDs
    /// </summary>
 
    [RfcField(AbapName = "MASK_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 64, Offset2 = 128)]
    [XmlElement("MASK_ID", Form=XmlSchemaForm.Unqualified)]
    public string Mask_Id
    { 
       get
       {
          return _Mask_Id;
       }
       set
       {
          _Mask_Id = value;
       }
    }
    private string _Mask_Id;


    /// <summary>
    /// Status profile for WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_STATUS_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 8, Length2 = 16, Offset = 88, Offset2 = 176)]
    [XmlElement("WBS_STATUS_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Status_Profile
    { 
       get
       {
          return _Wbs_Status_Profile;
       }
       set
       {
          _Wbs_Status_Profile = value;
       }
    }
    private string _Wbs_Status_Profile;


    /// <summary>
    /// Number of the responsible person (project manager)
    /// </summary>
 
    [RfcField(AbapName = "RESPONSIBLE_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 96, Offset2 = 192)]
    [XmlElement("RESPONSIBLE_NO", Form=XmlSchemaForm.Unqualified)]
    public string Responsible_No
    { 
       get
       {
          return _Responsible_No;
       }
       set
       {
          _Responsible_No = value;
       }
    }
    private string _Responsible_No;


    /// <summary>
    /// Applicant number
    /// </summary>
 
    [RfcField(AbapName = "APPLICANT_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 104, Offset2 = 208)]
    [XmlElement("APPLICANT_NO", Form=XmlSchemaForm.Unqualified)]
    public string Applicant_No
    { 
       get
       {
          return _Applicant_No;
       }
       set
       {
          _Applicant_No = value;
       }
    }
    private string _Applicant_No;


    /// <summary>
    /// Company code for the project
    /// </summary>
 
    [RfcField(AbapName = "COMPANY_CODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 112, Offset2 = 224)]
    [XmlElement("COMPANY_CODE", Form=XmlSchemaForm.Unqualified)]
    public string Company_Code
    { 
       get
       {
          return _Company_Code;
       }
       set
       {
          _Company_Code = value;
       }
    }
    private string _Company_Code;


    /// <summary>
    /// Business area for the project
    /// </summary>
 
    [RfcField(AbapName = "BUSINESS_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 116, Offset2 = 232)]
    [XmlElement("BUSINESS_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Business_Area
    { 
       get
       {
          return _Business_Area;
       }
       set
       {
          _Business_Area = value;
       }
    }
    private string _Business_Area;


    /// <summary>
    /// Controlling area for the project
    /// </summary>
 
    [RfcField(AbapName = "CONTROLLING_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 120, Offset2 = 240)]
    [XmlElement("CONTROLLING_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Controlling_Area
    { 
       get
       {
          return _Controlling_Area;
       }
       set
       {
          _Controlling_Area = value;
       }
    }
    private string _Controlling_Area;


    /// <summary>
    /// Profit Center
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 124, Offset2 = 248)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// WBS currency (project definition)
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 134, Offset2 = 268)]
    [XmlElement("PROJECT_CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Project_Currency
    { 
       get
       {
          return _Project_Currency;
       }
       set
       {
          _Project_Currency = value;
       }
    }
    private string _Project_Currency;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_CURRENCY_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 139, Offset2 = 278)]
    [XmlElement("PROJECT_CURRENCY_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Project_Currency_Iso
    { 
       get
       {
          return _Project_Currency_Iso;
       }
       set
       {
          _Project_Currency_Iso = value;
       }
    }
    private string _Project_Currency_Iso;


    /// <summary>
    /// Project planned start date
    /// </summary>
 
    [RfcField(AbapName = "START", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 142, Offset2 = 284)]
    [XmlElement("START", Form=XmlSchemaForm.Unqualified)]
    public string Start
    { 
       get
       {
          return _Start;
       }
       set
       {
          _Start = value;
       }
    }
    private string _Start;


    /// <summary>
    /// Project planned finish date
    /// </summary>
 
    [RfcField(AbapName = "FINISH", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 150, Offset2 = 300)]
    [XmlElement("FINISH", Form=XmlSchemaForm.Unqualified)]
    public string Finish
    { 
       get
       {
          return _Finish;
       }
       set
       {
          _Finish = value;
       }
    }
    private string _Finish;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 158, Offset2 = 316)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Factory calendar key
    /// </summary>
 
    [RfcField(AbapName = "CALENDAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 162, Offset2 = 324)]
    [XmlElement("CALENDAR", Form=XmlSchemaForm.Unqualified)]
    public string Calendar
    { 
       get
       {
          return _Calendar;
       }
       set
       {
          _Calendar = value;
       }
    }
    private string _Calendar;


    /// <summary>
    /// Planning method for project basic dates
    /// </summary>
 
    [RfcField(AbapName = "PLAN_BASIC", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 164, Offset2 = 328)]
    [XmlElement("PLAN_BASIC", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Basic
    { 
       get
       {
          return _Plan_Basic;
       }
       set
       {
          _Plan_Basic = value;
       }
    }
    private string _Plan_Basic;


    /// <summary>
    /// Planning method for project forecast dates
    /// </summary>
 
    [RfcField(AbapName = "PLAN_FCST", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 165, Offset2 = 330)]
    [XmlElement("PLAN_FCST", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Fcst
    { 
       get
       {
          return _Plan_Fcst;
       }
       set
       {
          _Plan_Fcst = value;
       }
    }
    private string _Plan_Fcst;


    /// <summary>
    /// Time unit in time scheduling
    /// </summary>
 
    [RfcField(AbapName = "TIME_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 166, Offset2 = 332)]
    [XmlElement("TIME_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Time_Unit
    { 
       get
       {
          return _Time_Unit;
       }
       set
       {
          _Time_Unit = value;
       }
    }
    private string _Time_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "TIME_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 169, Offset2 = 338)]
    [XmlElement("TIME_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Time_Unit_Iso
    { 
       get
       {
          return _Time_Unit_Iso;
       }
       set
       {
          _Time_Unit_Iso = value;
       }
    }
    private string _Time_Unit_Iso;


    /// <summary>
    /// Network profile
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 172, Offset2 = 344)]
    [XmlElement("NETWORK_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Network_Profile
    { 
       get
       {
          return _Network_Profile;
       }
       set
       {
          _Network_Profile = value;
       }
    }
    private string _Network_Profile;


    /// <summary>
    /// Project Profile
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 179, Offset2 = 358)]
    [XmlElement("PROJECT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Project_Profile
    { 
       get
       {
          return _Project_Profile;
       }
       set
       {
          _Project_Profile = value;
       }
    }
    private string _Project_Profile;


    /// <summary>
    /// Budget Profile
    /// </summary>
 
    [RfcField(AbapName = "BUDGET_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 186, Offset2 = 372)]
    [XmlElement("BUDGET_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Budget_Profile
    { 
       get
       {
          return _Budget_Profile;
       }
       set
       {
          _Budget_Profile = value;
       }
    }
    private string _Budget_Profile;


    /// <summary>
    /// Project stock
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_STOCK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 192, Offset2 = 384)]
    [XmlElement("PROJECT_STOCK", Form=XmlSchemaForm.Unqualified)]
    public string Project_Stock
    { 
       get
       {
          return _Project_Stock;
       }
       set
       {
          _Project_Stock = value;
       }
    }
    private string _Project_Stock;


    /// <summary>
    /// Object class, language-dependent
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 193, Offset2 = 386)]
    [XmlElement("OBJECTCLASS", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass
    { 
       get
       {
          return _Objectclass;
       }
       set
       {
          _Objectclass = value;
       }
    }
    private string _Objectclass;


    /// <summary>
    /// Statistical WBS element
    /// </summary>
 
    [RfcField(AbapName = "STATISTICAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 198, Offset2 = 396)]
    [XmlElement("STATISTICAL", Form=XmlSchemaForm.Unqualified)]
    public string Statistical
    { 
       get
       {
          return _Statistical;
       }
       set
       {
          _Statistical = value;
       }
    }
    private string _Statistical;


    /// <summary>
    /// Tax Jurisdiction
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 199, Offset2 = 398)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Interest Profile for Project/Order Interest Calculation
    /// </summary>
 
    [RfcField(AbapName = "INTEREST_PROF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 214, Offset2 = 428)]
    [XmlElement("INTEREST_PROF", Form=XmlSchemaForm.Unqualified)]
    public string Interest_Prof
    { 
       get
       {
          return _Interest_Prof;
       }
       set
       {
          _Interest_Prof = value;
       }
    }
    private string _Interest_Prof;


    /// <summary>
    /// Profile for WBS scheduling
    /// </summary>
 
    [RfcField(AbapName = "WBS_SCHED_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 221, Offset2 = 442)]
    [XmlElement("WBS_SCHED_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Sched_Profile
    { 
       get
       {
          return _Wbs_Sched_Profile;
       }
       set
       {
          _Wbs_Sched_Profile = value;
       }
    }
    private string _Wbs_Sched_Profile;


    /// <summary>
    /// Investment measure profile
    /// </summary>
 
    [RfcField(AbapName = "INVEST_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 233, Offset2 = 466)]
    [XmlElement("INVEST_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Invest_Profile
    { 
       get
       {
          return _Invest_Profile;
       }
       set
       {
          _Invest_Profile = value;
       }
    }
    private string _Invest_Profile;


    /// <summary>
    /// Results Analysis Key
    /// </summary>
 
    [RfcField(AbapName = "RES_ANAL_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 239, Offset2 = 478)]
    [XmlElement("RES_ANAL_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Res_Anal_Key
    { 
       get
       {
          return _Res_Anal_Key;
       }
       set
       {
          _Res_Anal_Key = value;
       }
    }
    private string _Res_Anal_Key;


    /// <summary>
    /// Planning profile
    /// </summary>
 
    [RfcField(AbapName = "PLAN_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 245, Offset2 = 490)]
    [XmlElement("PLAN_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Profile
    { 
       get
       {
          return _Plan_Profile;
       }
       set
       {
          _Plan_Profile = value;
       }
    }
    private string _Plan_Profile;


    /// <summary>
    /// Indicator for Integrated Planning
    /// </summary>
 
    [RfcField(AbapName = "PLANINTEGRATED", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 251, Offset2 = 502)]
    [XmlElement("PLANINTEGRATED", Form=XmlSchemaForm.Unqualified)]
    public string Planintegrated
    { 
       get
       {
          return _Planintegrated;
       }
       set
       {
          _Planintegrated = value;
       }
    }
    private string _Planintegrated;


    /// <summary>
    /// Valuation of Special Stock
    /// </summary>
 
    [RfcField(AbapName = "VALUATION_SPEC_STOCK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 252, Offset2 = 504)]
    [XmlElement("VALUATION_SPEC_STOCK", Form=XmlSchemaForm.Unqualified)]
    public string Valuation_Spec_Stock
    { 
       get
       {
          return _Valuation_Spec_Stock;
       }
       set
       {
          _Valuation_Spec_Stock = value;
       }
    }
    private string _Valuation_Spec_Stock;


    /// <summary>
    /// Simulation profile
    /// </summary>
 
    [RfcField(AbapName = "SIMULATION_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 253, Offset2 = 506)]
    [XmlElement("SIMULATION_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Simulation_Profile
    { 
       get
       {
          return _Simulation_Profile;
       }
       set
       {
          _Simulation_Profile = value;
       }
    }
    private string _Simulation_Profile;


    /// <summary>
    /// Indicator: Automatic requirements grouping
    /// </summary>
 
    [RfcField(AbapName = "GROUPING_INDICATOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 260, Offset2 = 520)]
    [XmlElement("GROUPING_INDICATOR", Form=XmlSchemaForm.Unqualified)]
    public string Grouping_Indicator
    { 
       get
       {
          return _Grouping_Indicator;
       }
       set
       {
          _Grouping_Indicator = value;
       }
    }
    private string _Grouping_Indicator;


    /// <summary>
    /// Location
    /// </summary>
 
    [RfcField(AbapName = "LOCATION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 261, Offset2 = 522)]
    [XmlElement("LOCATION", Form=XmlSchemaForm.Unqualified)]
    public string Location
    { 
       get
       {
          return _Location;
       }
       set
       {
          _Location = value;
       }
    }
    private string _Location;


    /// <summary>
    /// Partner Determination Procedure
    /// </summary>
 
    [RfcField(AbapName = "PARTNER_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 271, Offset2 = 542)]
    [XmlElement("PARTNER_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Partner_Profile
    { 
       get
       {
          return _Partner_Profile;
       }
       set
       {
          _Partner_Profile = value;
       }
    }
    private string _Partner_Profile;


    /// <summary>
    /// Joint Venture
    /// </summary>
 
    [RfcField(AbapName = "VENTURE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 275, Offset2 = 550)]
    [XmlElement("VENTURE", Form=XmlSchemaForm.Unqualified)]
    public string Venture
    { 
       get
       {
          return _Venture;
       }
       set
       {
          _Venture = value;
       }
    }
    private string _Venture;


    /// <summary>
    /// Recovery Indicator
    /// </summary>
 
    [RfcField(AbapName = "REC_IND", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 281, Offset2 = 562)]
    [XmlElement("REC_IND", Form=XmlSchemaForm.Unqualified)]
    public string Rec_Ind
    { 
       get
       {
          return _Rec_Ind;
       }
       set
       {
          _Rec_Ind = value;
       }
    }
    private string _Rec_Ind;


    /// <summary>
    /// Equity type
    /// </summary>
 
    [RfcField(AbapName = "EQUITY_TYP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 283, Offset2 = 566)]
    [XmlElement("EQUITY_TYP", Form=XmlSchemaForm.Unqualified)]
    public string Equity_Typ
    { 
       get
       {
          return _Equity_Typ;
       }
       set
       {
          _Equity_Typ = value;
       }
    }
    private string _Equity_Typ;


    /// <summary>
    /// Joint Venture Object Type
    /// </summary>
 
    [RfcField(AbapName = "JV_OTYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 286, Offset2 = 572)]
    [XmlElement("JV_OTYPE", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Otype
    { 
       get
       {
          return _Jv_Otype;
       }
       set
       {
          _Jv_Otype = value;
       }
    }
    private string _Jv_Otype;


    /// <summary>
    /// JIB/JIBE Class
    /// </summary>
 
    [RfcField(AbapName = "JV_JIBCL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 290, Offset2 = 580)]
    [XmlElement("JV_JIBCL", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jibcl
    { 
       get
       {
          return _Jv_Jibcl;
       }
       set
       {
          _Jv_Jibcl = value;
       }
    }
    private string _Jv_Jibcl;


    /// <summary>
    /// JIB/JIBE Subclass A
    /// </summary>
 
    [RfcField(AbapName = "JV_JIBSA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 293, Offset2 = 586)]
    [XmlElement("JV_JIBSA", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jibsa
    { 
       get
       {
          return _Jv_Jibsa;
       }
       set
       {
          _Jv_Jibsa = value;
       }
    }
    private string _Jv_Jibsa;


    /// <summary>
    /// Scheduling scenario
    /// </summary>
 
    [RfcField(AbapName = "SCHED_SCENARIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 298, Offset2 = 596)]
    [XmlElement("SCHED_SCENARIO", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Scenario
    { 
       get
       {
          return _Sched_Scenario;
       }
       set
       {
          _Sched_Scenario = value;
       }
    }
    private string _Sched_Scenario;


    /// <summary>
    /// Forecast start date of project definition
    /// </summary>
 
    [RfcField(AbapName = "FCST_START", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 299, Offset2 = 598)]
    [XmlElement("FCST_START", Form=XmlSchemaForm.Unqualified)]
    public string Fcst_Start
    { 
       get
       {
          return _Fcst_Start;
       }
       set
       {
          _Fcst_Start = value;
       }
    }
    private string _Fcst_Start;


    /// <summary>
    /// Forecast finish date for project definition
    /// </summary>
 
    [RfcField(AbapName = "FCST_FINISH", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 307, Offset2 = 614)]
    [XmlElement("FCST_FINISH", Form=XmlSchemaForm.Unqualified)]
    public string Fcst_Finish
    { 
       get
       {
          return _Fcst_Finish;
       }
       set
       {
          _Fcst_Finish = value;
       }
    }
    private string _Fcst_Finish;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 315, Offset2 = 630)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Sales Organization
    /// </summary>
 
    [RfcField(AbapName = "SALESORG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 331, Offset2 = 662)]
    [XmlElement("SALESORG", Form=XmlSchemaForm.Unqualified)]
    public string Salesorg
    { 
       get
       {
          return _Salesorg;
       }
       set
       {
          _Salesorg = value;
       }
    }
    private string _Salesorg;


    /// <summary>
    /// Distribution Channel
    /// </summary>
 
    [RfcField(AbapName = "DISTR_CHAN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 335, Offset2 = 670)]
    [XmlElement("DISTR_CHAN", Form=XmlSchemaForm.Unqualified)]
    public string Distr_Chan
    { 
       get
       {
          return _Distr_Chan;
       }
       set
       {
          _Distr_Chan = value;
       }
    }
    private string _Distr_Chan;


    /// <summary>
    /// Division
    /// </summary>
 
    [RfcField(AbapName = "DIVISION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 337, Offset2 = 674)]
    [XmlElement("DIVISION", Form=XmlSchemaForm.Unqualified)]
    public string Division
    { 
       get
       {
          return _Division;
       }
       set
       {
          _Division = value;
       }
    }
    private string _Division;


    /// <summary>
    /// Dynamic Item Processor Profile
    /// </summary>
 
    [RfcField(AbapName = "DLI_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 8, Length2 = 16, Offset = 339, Offset2 = 678)]
    [XmlElement("DLI_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Dli_Profile
    { 
       get
       {
          return _Dli_Profile;
       }
       set
       {
          _Dli_Profile = value;
       }
    }
    private string _Dli_Profile;


    /// <summary>
    /// Language Key
    /// </summary>
 
    [RfcField(AbapName = "LANGU", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 347, Offset2 = 694)]
    [XmlElement("LANGU", Form=XmlSchemaForm.Unqualified)]
    public string Langu
    { 
       get
       {
          return _Langu;
       }
       set
       {
          _Langu = value;
       }
    }
    private string _Langu;


    /// <summary>
    /// Language according to ISO 639
    /// </summary>
 
    [RfcField(AbapName = "LANGU_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 348, Offset2 = 696)]
    [XmlElement("LANGU_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Langu_Iso
    { 
       get
       {
          return _Langu_Iso;
       }
       set
       {
          _Langu_Iso = value;
       }
    }
    private string _Langu_Iso;


    /// <summary>
    /// System Status Text
    /// </summary>
 
    [RfcField(AbapName = "SYSTEM_STATUS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 350, Offset2 = 700)]
    [XmlElement("SYSTEM_STATUS", Form=XmlSchemaForm.Unqualified)]
    public string System_Status
    { 
       get
       {
          return _System_Status;
       }
       set
       {
          _System_Status = value;
       }
    }
    private string _System_Status;


    /// <summary>
    /// Network assignment
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_ASSIGNMENT", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 354, Offset2 = 708)]
    [XmlElement("NETWORK_ASSIGNMENT", Form=XmlSchemaForm.Unqualified)]
    public string Network_Assignment
    { 
       get
       {
          return _Network_Assignment;
       }
       set
       {
          _Network_Assignment = value;
       }
    }
    private string _Network_Assignment;


    /// <summary>
    /// Status Profile
    /// </summary>
 
    [RfcField(AbapName = "STAT_PROF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 8, Length2 = 16, Offset = 355, Offset2 = 710)]
    [XmlElement("STAT_PROF", Form=XmlSchemaForm.Unqualified)]
    public string Stat_Prof
    { 
       get
       {
          return _Stat_Prof;
       }
       set
       {
          _Stat_Prof = value;
       }
    }
    private string _Stat_Prof;

  }

}
