
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI Structure  Milestones under Activity (Update Fields)
  /// </summary>
  [RfcStructure(AbapName ="BAPI_ACT_MILESTONE_UPD" , Length = 26, Length2 = 52)]
  [Serializable]
  public class BAPI_ACT_MILESTONE_UPD : SAPStructure
  {
   

    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "MILESTONE_NUMBER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("MILESTONE_NUMBER", Form=XmlSchemaForm.Unqualified)]
    public string Milestone_Number
    { 
       get
       {
          return _Milestone_Number;
       }
       set
       {
          _Milestone_Number = value;
       }
    }
    private string _Milestone_Number;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 1, Offset2 = 2)]
    [XmlElement("NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Network
    { 
       get
       {
          return _Network;
       }
       set
       {
          _Network = value;
       }
    }
    private string _Network;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 2, Offset2 = 4)]
    [XmlElement("ACTIVITY", Form=XmlSchemaForm.Unqualified)]
    public string Activity
    { 
       get
       {
          return _Activity;
       }
       set
       {
          _Activity = value;
       }
    }
    private string _Activity;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "MILESTONE_USAGE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 3, Offset2 = 6)]
    [XmlElement("MILESTONE_USAGE", Form=XmlSchemaForm.Unqualified)]
    public string Milestone_Usage
    { 
       get
       {
          return _Milestone_Usage;
       }
       set
       {
          _Milestone_Usage = value;
       }
    }
    private string _Milestone_Usage;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 4, Offset2 = 8)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SCHED_MILESTONE_DATE_BASIC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 5, Offset2 = 10)]
    [XmlElement("SCHED_MILESTONE_DATE_BASIC", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Milestone_Date_Basic
    { 
       get
       {
          return _Sched_Milestone_Date_Basic;
       }
       set
       {
          _Sched_Milestone_Date_Basic = value;
       }
    }
    private string _Sched_Milestone_Date_Basic;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SCHED_MILESTONE_TIME_BASIC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 6, Offset2 = 12)]
    [XmlElement("SCHED_MILESTONE_TIME_BASIC", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Milestone_Time_Basic
    { 
       get
       {
          return _Sched_Milestone_Time_Basic;
       }
       set
       {
          _Sched_Milestone_Time_Basic = value;
       }
    }
    private string _Sched_Milestone_Time_Basic;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SCHED_MILESTONE_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 7, Offset2 = 14)]
    [XmlElement("SCHED_MILESTONE_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Milestone_Date_Forecast
    { 
       get
       {
          return _Sched_Milestone_Date_Forecast;
       }
       set
       {
          _Sched_Milestone_Date_Forecast = value;
       }
    }
    private string _Sched_Milestone_Date_Forecast;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SCHED_MILESTONE_TIME_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 8, Offset2 = 16)]
    [XmlElement("SCHED_MILESTONE_TIME_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Milestone_Time_Forecast
    { 
       get
       {
          return _Sched_Milestone_Time_Forecast;
       }
       set
       {
          _Sched_Milestone_Time_Forecast = value;
       }
    }
    private string _Sched_Milestone_Time_Forecast;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FIXED_MILESTONE_DATE_BASIC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 9, Offset2 = 18)]
    [XmlElement("FIXED_MILESTONE_DATE_BASIC", Form=XmlSchemaForm.Unqualified)]
    public string Fixed_Milestone_Date_Basic
    { 
       get
       {
          return _Fixed_Milestone_Date_Basic;
       }
       set
       {
          _Fixed_Milestone_Date_Basic = value;
       }
    }
    private string _Fixed_Milestone_Date_Basic;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FIXED_MILESTONE_TIME_BASIC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 10, Offset2 = 20)]
    [XmlElement("FIXED_MILESTONE_TIME_BASIC", Form=XmlSchemaForm.Unqualified)]
    public string Fixed_Milestone_Time_Basic
    { 
       get
       {
          return _Fixed_Milestone_Time_Basic;
       }
       set
       {
          _Fixed_Milestone_Time_Basic = value;
       }
    }
    private string _Fixed_Milestone_Time_Basic;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FIXED_MILESTONE_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 11, Offset2 = 22)]
    [XmlElement("FIXED_MILESTONE_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Fixed_Milestone_Date_Forecast
    { 
       get
       {
          return _Fixed_Milestone_Date_Forecast;
       }
       set
       {
          _Fixed_Milestone_Date_Forecast = value;
       }
    }
    private string _Fixed_Milestone_Date_Forecast;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FIXED_MILESTONE_TIME_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 12, Offset2 = 24)]
    [XmlElement("FIXED_MILESTONE_TIME_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Fixed_Milestone_Time_Forecast
    { 
       get
       {
          return _Fixed_Milestone_Time_Forecast;
       }
       set
       {
          _Fixed_Milestone_Time_Forecast = value;
       }
    }
    private string _Fixed_Milestone_Time_Forecast;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 13, Offset2 = 26)]
    [XmlElement("ACTUAL_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Actual_Date
    { 
       get
       {
          return _Actual_Date;
       }
       set
       {
          _Actual_Date = value;
       }
    }
    private string _Actual_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTUAL_TIME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 14, Offset2 = 28)]
    [XmlElement("ACTUAL_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Actual_Time
    { 
       get
       {
          return _Actual_Time;
       }
       set
       {
          _Actual_Time = value;
       }
    }
    private string _Actual_Time;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_DATES_INDICATOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 15, Offset2 = 30)]
    [XmlElement("LATEST_DATES_INDICATOR", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Dates_Indicator
    { 
       get
       {
          return _Latest_Dates_Indicator;
       }
       set
       {
          _Latest_Dates_Indicator = value;
       }
    }
    private string _Latest_Dates_Indicator;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_START_END_INDICATOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 16, Offset2 = 32)]
    [XmlElement("OFFSET_START_END_INDICATOR", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Start_End_Indicator
    { 
       get
       {
          return _Offset_Start_End_Indicator;
       }
       set
       {
          _Offset_Start_End_Indicator = value;
       }
    }
    private string _Offset_Start_End_Indicator;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_MILESTONE_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 17, Offset2 = 34)]
    [XmlElement("OFFSET_MILESTONE_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Milestone_Date
    { 
       get
       {
          return _Offset_Milestone_Date;
       }
       set
       {
          _Offset_Milestone_Date = value;
       }
    }
    private string _Offset_Milestone_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_MILESTONE_DATE_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 18, Offset2 = 36)]
    [XmlElement("OFFSET_MILESTONE_DATE_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Milestone_Date_Unit
    { 
       get
       {
          return _Offset_Milestone_Date_Unit;
       }
       set
       {
          _Offset_Milestone_Date_Unit = value;
       }
    }
    private string _Offset_Milestone_Date_Unit;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_MILESTONE_DATE_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 19, Offset2 = 38)]
    [XmlElement("OFFSET_MILESTONE_DATE_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Milestone_Date_Unit_Iso
    { 
       get
       {
          return _Offset_Milestone_Date_Unit_Iso;
       }
       set
       {
          _Offset_Milestone_Date_Unit_Iso = value;
       }
    }
    private string _Offset_Milestone_Date_Unit_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_PERCENTAGE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 20, Offset2 = 40)]
    [XmlElement("OFFSET_PERCENTAGE", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Percentage
    { 
       get
       {
          return _Offset_Percentage;
       }
       set
       {
          _Offset_Percentage = value;
       }
    }
    private string _Offset_Percentage;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "TREND_ANALYSIS_INDICATOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 21, Offset2 = 42)]
    [XmlElement("TREND_ANALYSIS_INDICATOR", Form=XmlSchemaForm.Unqualified)]
    public string Trend_Analysis_Indicator
    { 
       get
       {
          return _Trend_Analysis_Indicator;
       }
       set
       {
          _Trend_Analysis_Indicator = value;
       }
    }
    private string _Trend_Analysis_Indicator;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARNED_VALUE_INDICATOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 22, Offset2 = 44)]
    [XmlElement("EARNED_VALUE_INDICATOR", Form=XmlSchemaForm.Unqualified)]
    public string Earned_Value_Indicator
    { 
       get
       {
          return _Earned_Value_Indicator;
       }
       set
       {
          _Earned_Value_Indicator = value;
       }
    }
    private string _Earned_Value_Indicator;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PERCENTAGE_OF_COMPLETION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 23, Offset2 = 46)]
    [XmlElement("PERCENTAGE_OF_COMPLETION", Form=XmlSchemaForm.Unqualified)]
    public string Percentage_Of_Completion
    { 
       get
       {
          return _Percentage_Of_Completion;
       }
       set
       {
          _Percentage_Of_Completion = value;
       }
    }
    private string _Percentage_Of_Completion;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SALES_DOC_DATE_INIDICATOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 24, Offset2 = 48)]
    [XmlElement("SALES_DOC_DATE_INIDICATOR", Form=XmlSchemaForm.Unqualified)]
    public string Sales_Doc_Date_Inidicator
    { 
       get
       {
          return _Sales_Doc_Date_Inidicator;
       }
       set
       {
          _Sales_Doc_Date_Inidicator = value;
       }
    }
    private string _Sales_Doc_Date_Inidicator;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "INVOICE_PERCENTAGE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 25, Offset2 = 50)]
    [XmlElement("INVOICE_PERCENTAGE", Form=XmlSchemaForm.Unqualified)]
    public string Invoice_Percentage
    { 
       get
       {
          return _Invoice_Percentage;
       }
       set
       {
          _Invoice_Percentage = value;
       }
    }
    private string _Invoice_Percentage;

  }

}
