
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Update Structure: ActivityElement
  /// </summary>
  [RfcStructure(AbapName ="BAPI_ACT_ELEMENT_UPD" , Length = 81, Length2 = 162)]
  [Serializable]
  public class BAPI_ACT_ELEMENT_UPD : SAPStructure
  {
   

    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Network
    { 
       get
       {
          return _Network;
       }
       set
       {
          _Network = value;
       }
    }
    private string _Network;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 1, Offset2 = 2)]
    [XmlElement("ACTIVITY", Form=XmlSchemaForm.Unqualified)]
    public string Activity
    { 
       get
       {
          return _Activity;
       }
       set
       {
          _Activity = value;
       }
    }
    private string _Activity;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 2, Offset2 = 4)]
    [XmlElement("ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Element
    { 
       get
       {
          return _Element;
       }
       set
       {
          _Element = value;
       }
    }
    private string _Element;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "CONTROL_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 3, Offset2 = 6)]
    [XmlElement("CONTROL_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Control_Key
    { 
       get
       {
          return _Control_Key;
       }
       set
       {
          _Control_Key = value;
       }
    }
    private string _Control_Key;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "WORK_CNTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 4, Offset2 = 8)]
    [XmlElement("WORK_CNTR", Form=XmlSchemaForm.Unqualified)]
    public string Work_Cntr
    { 
       get
       {
          return _Work_Cntr;
       }
       set
       {
          _Work_Cntr = value;
       }
    }
    private string _Work_Cntr;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 5, Offset2 = 10)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 6, Offset2 = 12)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "VENDOR_NO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 7, Offset2 = 14)]
    [XmlElement("VENDOR_NO", Form=XmlSchemaForm.Unqualified)]
    public string Vendor_No
    { 
       get
       {
          return _Vendor_No;
       }
       set
       {
          _Vendor_No = value;
       }
    }
    private string _Vendor_No;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PRICE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 8, Offset2 = 16)]
    [XmlElement("PRICE", Form=XmlSchemaForm.Unqualified)]
    public string Price
    { 
       get
       {
          return _Price;
       }
       set
       {
          _Price = value;
       }
    }
    private string _Price;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PRICE_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 9, Offset2 = 18)]
    [XmlElement("PRICE_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Price_Unit
    { 
       get
       {
          return _Price_Unit;
       }
       set
       {
          _Price_Unit = value;
       }
    }
    private string _Price_Unit;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "COST_ELEM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 10, Offset2 = 20)]
    [XmlElement("COST_ELEM", Form=XmlSchemaForm.Unqualified)]
    public string Cost_Elem
    { 
       get
       {
          return _Cost_Elem;
       }
       set
       {
          _Cost_Elem = value;
       }
    }
    private string _Cost_Elem;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 11, Offset2 = 22)]
    [XmlElement("CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Currency
    { 
       get
       {
          return _Currency;
       }
       set
       {
          _Currency = value;
       }
    }
    private string _Currency;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "CURRENCY_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 12, Offset2 = 24)]
    [XmlElement("CURRENCY_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Currency_Iso
    { 
       get
       {
          return _Currency_Iso;
       }
       set
       {
          _Currency_Iso = value;
       }
    }
    private string _Currency_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "INFO_REC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 13, Offset2 = 26)]
    [XmlElement("INFO_REC", Form=XmlSchemaForm.Unqualified)]
    public string Info_Rec
    { 
       get
       {
          return _Info_Rec;
       }
       set
       {
          _Info_Rec = value;
       }
    }
    private string _Info_Rec;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PURCH_ORG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 14, Offset2 = 28)]
    [XmlElement("PURCH_ORG", Form=XmlSchemaForm.Unqualified)]
    public string Purch_Org
    { 
       get
       {
          return _Purch_Org;
       }
       set
       {
          _Purch_Org = value;
       }
    }
    private string _Purch_Org;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PUR_GROUP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 15, Offset2 = 30)]
    [XmlElement("PUR_GROUP", Form=XmlSchemaForm.Unqualified)]
    public string Pur_Group
    { 
       get
       {
          return _Pur_Group;
       }
       set
       {
          _Pur_Group = value;
       }
    }
    private string _Pur_Group;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "MATL_GROUP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 16, Offset2 = 32)]
    [XmlElement("MATL_GROUP", Form=XmlSchemaForm.Unqualified)]
    public string Matl_Group
    { 
       get
       {
          return _Matl_Group;
       }
       set
       {
          _Matl_Group = value;
       }
    }
    private string _Matl_Group;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NUMBER_OF_CAPACITIES", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 17, Offset2 = 34)]
    [XmlElement("NUMBER_OF_CAPACITIES", Form=XmlSchemaForm.Unqualified)]
    public string Number_Of_Capacities
    { 
       get
       {
          return _Number_Of_Capacities;
       }
       set
       {
          _Number_Of_Capacities = value;
       }
    }
    private string _Number_Of_Capacities;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PERCENT_OF_WORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 18, Offset2 = 36)]
    [XmlElement("PERCENT_OF_WORK", Form=XmlSchemaForm.Unqualified)]
    public string Percent_Of_Work
    { 
       get
       {
          return _Percent_Of_Work;
       }
       set
       {
          _Percent_Of_Work = value;
       }
    }
    private string _Percent_Of_Work;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTTYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 19, Offset2 = 38)]
    [XmlElement("ACTTYPE", Form=XmlSchemaForm.Unqualified)]
    public string Acttype
    { 
       get
       {
          return _Acttype;
       }
       set
       {
          _Acttype = value;
       }
    }
    private string _Acttype;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_COSTS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 20, Offset2 = 40)]
    [XmlElement("ACTIVITY_COSTS", Form=XmlSchemaForm.Unqualified)]
    public string Activity_Costs
    { 
       get
       {
          return _Activity_Costs;
       }
       set
       {
          _Activity_Costs = value;
       }
    }
    private string _Activity_Costs;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 21, Offset2 = 42)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "WBS_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 22, Offset2 = 44)]
    [XmlElement("WBS_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Element
    { 
       get
       {
          return _Wbs_Element;
       }
       set
       {
          _Wbs_Element = value;
       }
    }
    private string _Wbs_Element;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DISTRIBUTING_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 23, Offset2 = 46)]
    [XmlElement("DISTRIBUTING_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Distributing_Key
    { 
       get
       {
          return _Distributing_Key;
       }
       set
       {
          _Distributing_Key = value;
       }
    }
    private string _Distributing_Key;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 24, Offset2 = 48)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 25, Offset2 = 50)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NOT_MRP_APPLICABLE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 26, Offset2 = 52)]
    [XmlElement("NOT_MRP_APPLICABLE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Mrp_Applicable
    { 
       get
       {
          return _Not_Mrp_Applicable;
       }
       set
       {
          _Not_Mrp_Applicable = value;
       }
    }
    private string _Not_Mrp_Applicable;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_SUMMARIZATION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 27, Offset2 = 54)]
    [XmlElement("PROJECT_SUMMARIZATION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Summarization
    { 
       get
       {
          return _Project_Summarization;
       }
       set
       {
          _Project_Summarization = value;
       }
    }
    private string _Project_Summarization;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OPERATION_MEASURE_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 28, Offset2 = 56)]
    [XmlElement("OPERATION_MEASURE_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Operation_Measure_Unit
    { 
       get
       {
          return _Operation_Measure_Unit;
       }
       set
       {
          _Operation_Measure_Unit = value;
       }
    }
    private string _Operation_Measure_Unit;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OPERATION_MEASURE_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 29, Offset2 = 58)]
    [XmlElement("OPERATION_MEASURE_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Operation_Measure_Unit_Iso
    { 
       get
       {
          return _Operation_Measure_Unit_Iso;
       }
       set
       {
          _Operation_Measure_Unit_Iso = value;
       }
    }
    private string _Operation_Measure_Unit_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLND_DELRY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 30, Offset2 = 60)]
    [XmlElement("PLND_DELRY", Form=XmlSchemaForm.Unqualified)]
    public string Plnd_Delry
    { 
       get
       {
          return _Plnd_Delry;
       }
       set
       {
          _Plnd_Delry = value;
       }
    }
    private string _Plnd_Delry;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "WORK_ACTIVITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 31, Offset2 = 62)]
    [XmlElement("WORK_ACTIVITY", Form=XmlSchemaForm.Unqualified)]
    public string Work_Activity
    { 
       get
       {
          return _Work_Activity;
       }
       set
       {
          _Work_Activity = value;
       }
    }
    private string _Work_Activity;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "UN_WORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 32, Offset2 = 64)]
    [XmlElement("UN_WORK", Form=XmlSchemaForm.Unqualified)]
    public string Un_Work
    { 
       get
       {
          return _Un_Work;
       }
       set
       {
          _Un_Work = value;
       }
    }
    private string _Un_Work;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "UN_WORK_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 33, Offset2 = 66)]
    [XmlElement("UN_WORK_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Un_Work_Iso
    { 
       get
       {
          return _Un_Work_Iso;
       }
       set
       {
          _Un_Work_Iso = value;
       }
    }
    private string _Un_Work_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 34, Offset2 = 68)]
    [XmlElement("EARLY_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Date
    { 
       get
       {
          return _Early_Start_Date;
       }
       set
       {
          _Early_Start_Date = value;
       }
    }
    private string _Early_Start_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_TIME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 35, Offset2 = 70)]
    [XmlElement("EARLY_START_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Time
    { 
       get
       {
          return _Early_Start_Time;
       }
       set
       {
          _Early_Start_Time = value;
       }
    }
    private string _Early_Start_Time;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 36, Offset2 = 72)]
    [XmlElement("EARLY_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Date
    { 
       get
       {
          return _Early_Finish_Date;
       }
       set
       {
          _Early_Finish_Date = value;
       }
    }
    private string _Early_Finish_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_TIME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 37, Offset2 = 74)]
    [XmlElement("EARLY_FINISH_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Time
    { 
       get
       {
          return _Early_Finish_Time;
       }
       set
       {
          _Early_Finish_Time = value;
       }
    }
    private string _Early_Finish_Time;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 38, Offset2 = 76)]
    [XmlElement("LATEST_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Date
    { 
       get
       {
          return _Latest_Start_Date;
       }
       set
       {
          _Latest_Start_Date = value;
       }
    }
    private string _Latest_Start_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_TIME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 39, Offset2 = 78)]
    [XmlElement("LATEST_START_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Time
    { 
       get
       {
          return _Latest_Start_Time;
       }
       set
       {
          _Latest_Start_Time = value;
       }
    }
    private string _Latest_Start_Time;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 40, Offset2 = 80)]
    [XmlElement("LATEST_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Date
    { 
       get
       {
          return _Latest_Finish_Date;
       }
       set
       {
          _Latest_Finish_Date = value;
       }
    }
    private string _Latest_Finish_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_TIME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 41, Offset2 = 82)]
    [XmlElement("LATEST_FINISH_TIME", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Time
    { 
       get
       {
          return _Latest_Finish_Time;
       }
       set
       {
          _Latest_Finish_Time = value;
       }
    }
    private string _Latest_Finish_Time;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 42, Offset2 = 84)]
    [XmlElement("USER_FIELD_KEY", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Key
    { 
       get
       {
          return _User_Field_Key;
       }
       set
       {
          _User_Field_Key = value;
       }
    }
    private string _User_Field_Key;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR20_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 43, Offset2 = 86)]
    [XmlElement("USER_FIELD_CHAR20_1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char20_1
    { 
       get
       {
          return _User_Field_Char20_1;
       }
       set
       {
          _User_Field_Char20_1 = value;
       }
    }
    private string _User_Field_Char20_1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR20_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 44, Offset2 = 88)]
    [XmlElement("USER_FIELD_CHAR20_2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char20_2
    { 
       get
       {
          return _User_Field_Char20_2;
       }
       set
       {
          _User_Field_Char20_2 = value;
       }
    }
    private string _User_Field_Char20_2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR10_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 45, Offset2 = 90)]
    [XmlElement("USER_FIELD_CHAR10_1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char10_1
    { 
       get
       {
          return _User_Field_Char10_1;
       }
       set
       {
          _User_Field_Char10_1 = value;
       }
    }
    private string _User_Field_Char10_1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR10_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 46, Offset2 = 92)]
    [XmlElement("USER_FIELD_CHAR10_2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char10_2
    { 
       get
       {
          return _User_Field_Char10_2;
       }
       set
       {
          _User_Field_Char10_2 = value;
       }
    }
    private string _User_Field_Char10_2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_QUAN1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 47, Offset2 = 94)]
    [XmlElement("USER_FIELD_QUAN1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Quan1
    { 
       get
       {
          return _User_Field_Quan1;
       }
       set
       {
          _User_Field_Quan1 = value;
       }
    }
    private string _User_Field_Quan1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 48, Offset2 = 96)]
    [XmlElement("USER_FIELD_UNIT1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit1
    { 
       get
       {
          return _User_Field_Unit1;
       }
       set
       {
          _User_Field_Unit1 = value;
       }
    }
    private string _User_Field_Unit1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT1_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 49, Offset2 = 98)]
    [XmlElement("USER_FIELD_UNIT1_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit1_Iso
    { 
       get
       {
          return _User_Field_Unit1_Iso;
       }
       set
       {
          _User_Field_Unit1_Iso = value;
       }
    }
    private string _User_Field_Unit1_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_QUAN2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 50, Offset2 = 100)]
    [XmlElement("USER_FIELD_QUAN2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Quan2
    { 
       get
       {
          return _User_Field_Quan2;
       }
       set
       {
          _User_Field_Quan2 = value;
       }
    }
    private string _User_Field_Quan2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 51, Offset2 = 102)]
    [XmlElement("USER_FIELD_UNIT2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit2
    { 
       get
       {
          return _User_Field_Unit2;
       }
       set
       {
          _User_Field_Unit2 = value;
       }
    }
    private string _User_Field_Unit2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT2_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 52, Offset2 = 104)]
    [XmlElement("USER_FIELD_UNIT2_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit2_Iso
    { 
       get
       {
          return _User_Field_Unit2_Iso;
       }
       set
       {
          _User_Field_Unit2_Iso = value;
       }
    }
    private string _User_Field_Unit2_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CURR1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 53, Offset2 = 106)]
    [XmlElement("USER_FIELD_CURR1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Curr1
    { 
       get
       {
          return _User_Field_Curr1;
       }
       set
       {
          _User_Field_Curr1 = value;
       }
    }
    private string _User_Field_Curr1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 54, Offset2 = 108)]
    [XmlElement("USER_FIELD_CUKY1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky1
    { 
       get
       {
          return _User_Field_Cuky1;
       }
       set
       {
          _User_Field_Cuky1 = value;
       }
    }
    private string _User_Field_Cuky1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY1_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 55, Offset2 = 110)]
    [XmlElement("USER_FIELD_CUKY1_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky1_Iso
    { 
       get
       {
          return _User_Field_Cuky1_Iso;
       }
       set
       {
          _User_Field_Cuky1_Iso = value;
       }
    }
    private string _User_Field_Cuky1_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CURR2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 56, Offset2 = 112)]
    [XmlElement("USER_FIELD_CURR2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Curr2
    { 
       get
       {
          return _User_Field_Curr2;
       }
       set
       {
          _User_Field_Curr2 = value;
       }
    }
    private string _User_Field_Curr2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 57, Offset2 = 114)]
    [XmlElement("USER_FIELD_CUKY2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky2
    { 
       get
       {
          return _User_Field_Cuky2;
       }
       set
       {
          _User_Field_Cuky2 = value;
       }
    }
    private string _User_Field_Cuky2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY2_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 58, Offset2 = 116)]
    [XmlElement("USER_FIELD_CUKY2_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky2_Iso
    { 
       get
       {
          return _User_Field_Cuky2_Iso;
       }
       set
       {
          _User_Field_Cuky2_Iso = value;
       }
    }
    private string _User_Field_Cuky2_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_DATE1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 59, Offset2 = 118)]
    [XmlElement("USER_FIELD_DATE1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Date1
    { 
       get
       {
          return _User_Field_Date1;
       }
       set
       {
          _User_Field_Date1 = value;
       }
    }
    private string _User_Field_Date1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_DATE2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 60, Offset2 = 120)]
    [XmlElement("USER_FIELD_DATE2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Date2
    { 
       get
       {
          return _User_Field_Date2;
       }
       set
       {
          _User_Field_Date2 = value;
       }
    }
    private string _User_Field_Date2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_FLAG1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 61, Offset2 = 122)]
    [XmlElement("USER_FIELD_FLAG1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Flag1
    { 
       get
       {
          return _User_Field_Flag1;
       }
       set
       {
          _User_Field_Flag1 = value;
       }
    }
    private string _User_Field_Flag1;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_FLAG2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 62, Offset2 = 124)]
    [XmlElement("USER_FIELD_FLAG2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Flag2
    { 
       get
       {
          return _User_Field_Flag2;
       }
       set
       {
          _User_Field_Flag2 = value;
       }
    }
    private string _User_Field_Flag2;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_DATE_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 63, Offset2 = 126)]
    [XmlElement("EARLY_START_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Date_Fc
    { 
       get
       {
          return _Early_Start_Date_Fc;
       }
       set
       {
          _Early_Start_Date_Fc = value;
       }
    }
    private string _Early_Start_Date_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_START_TIME_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 64, Offset2 = 128)]
    [XmlElement("EARLY_START_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Start_Time_Fc
    { 
       get
       {
          return _Early_Start_Time_Fc;
       }
       set
       {
          _Early_Start_Time_Fc = value;
       }
    }
    private string _Early_Start_Time_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_DATE_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 65, Offset2 = 130)]
    [XmlElement("EARLY_FINISH_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Date_Fc
    { 
       get
       {
          return _Early_Finish_Date_Fc;
       }
       set
       {
          _Early_Finish_Date_Fc = value;
       }
    }
    private string _Early_Finish_Date_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EARLY_FINISH_TIME_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 66, Offset2 = 132)]
    [XmlElement("EARLY_FINISH_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Early_Finish_Time_Fc
    { 
       get
       {
          return _Early_Finish_Time_Fc;
       }
       set
       {
          _Early_Finish_Time_Fc = value;
       }
    }
    private string _Early_Finish_Time_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_DATE_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 67, Offset2 = 134)]
    [XmlElement("LATEST_START_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Date_Fc
    { 
       get
       {
          return _Latest_Start_Date_Fc;
       }
       set
       {
          _Latest_Start_Date_Fc = value;
       }
    }
    private string _Latest_Start_Date_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_START_TIME_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 68, Offset2 = 136)]
    [XmlElement("LATEST_START_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Start_Time_Fc
    { 
       get
       {
          return _Latest_Start_Time_Fc;
       }
       set
       {
          _Latest_Start_Time_Fc = value;
       }
    }
    private string _Latest_Start_Time_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_DATE_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 69, Offset2 = 138)]
    [XmlElement("LATEST_FINISH_DATE_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Date_Fc
    { 
       get
       {
          return _Latest_Finish_Date_Fc;
       }
       set
       {
          _Latest_Finish_Date_Fc = value;
       }
    }
    private string _Latest_Finish_Date_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "LATEST_FINISH_TIME_FC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 70, Offset2 = 140)]
    [XmlElement("LATEST_FINISH_TIME_FC", Form=XmlSchemaForm.Unqualified)]
    public string Latest_Finish_Time_Fc
    { 
       get
       {
          return _Latest_Finish_Time_Fc;
       }
       set
       {
          _Latest_Finish_Time_Fc = value;
       }
    }
    private string _Latest_Finish_Time_Fc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 71, Offset2 = 142)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_START", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 72, Offset2 = 144)]
    [XmlElement("OFFSET_START", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Start
    { 
       get
       {
          return _Offset_Start;
       }
       set
       {
          _Offset_Start = value;
       }
    }
    private string _Offset_Start;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_START_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 73, Offset2 = 146)]
    [XmlElement("OFFSET_START_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Start_Unit
    { 
       get
       {
          return _Offset_Start_Unit;
       }
       set
       {
          _Offset_Start_Unit = value;
       }
    }
    private string _Offset_Start_Unit;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_START_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 74, Offset2 = 148)]
    [XmlElement("OFFSET_START_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Offset_Start_Unit_Iso
    { 
       get
       {
          return _Offset_Start_Unit_Iso;
       }
       set
       {
          _Offset_Start_Unit_Iso = value;
       }
    }
    private string _Offset_Start_Unit_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_END", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 75, Offset2 = 150)]
    [XmlElement("OFFSET_END", Form=XmlSchemaForm.Unqualified)]
    public string Offset_End
    { 
       get
       {
          return _Offset_End;
       }
       set
       {
          _Offset_End = value;
       }
    }
    private string _Offset_End;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_END_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 76, Offset2 = 152)]
    [XmlElement("OFFSET_END_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Offset_End_Unit
    { 
       get
       {
          return _Offset_End_Unit;
       }
       set
       {
          _Offset_End_Unit = value;
       }
    }
    private string _Offset_End_Unit;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_END_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 77, Offset2 = 154)]
    [XmlElement("OFFSET_END_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Offset_End_Unit_Iso
    { 
       get
       {
          return _Offset_End_Unit_Iso;
       }
       set
       {
          _Offset_End_Unit_Iso = value;
       }
    }
    private string _Offset_End_Unit_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 78, Offset2 = 156)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 79, Offset2 = 158)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PERS_NO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 80, Offset2 = 160)]
    [XmlElement("PERS_NO", Form=XmlSchemaForm.Unqualified)]
    public string Pers_No
    { 
       get
       {
          return _Pers_No;
       }
       set
       {
          _Pers_No = value;
       }
    }
    private string _Pers_No;

  }

}
