
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI Structure WBS Elements incl. some Date Fields PRTE
  /// </summary>
  [RfcStructure(AbapName ="BAPI_WBS_ELEMENT" , Length = 588, Length2 = 1146)]
  [Serializable]
  public class BAPI_WBS_ELEMENT : SAPStructure
  {
   

    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "WBS_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 0, Offset2 = 0)]
    [XmlElement("WBS_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Element
    { 
       get
       {
          return _Wbs_Element;
       }
       set
       {
          _Wbs_Element = value;
       }
    }
    private string _Wbs_Element;


    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 24, Offset2 = 48)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// PS: Short description (1st text line)
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 48, Offset2 = 96)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;


    /// <summary>
    /// WBS element short identification
    /// </summary>
 
    [RfcField(AbapName = "SHORT_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 88, Offset2 = 176)]
    [XmlElement("SHORT_ID", Form=XmlSchemaForm.Unqualified)]
    public string Short_Id
    { 
       get
       {
          return _Short_Id;
       }
       set
       {
          _Short_Id = value;
       }
    }
    private string _Short_Id;


    /// <summary>
    /// Number of the responsible person (project manager)
    /// </summary>
 
    [RfcField(AbapName = "RESPONSIBLE_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 104, Offset2 = 208)]
    [XmlElement("RESPONSIBLE_NO", Form=XmlSchemaForm.Unqualified)]
    public string Responsible_No
    { 
       get
       {
          return _Responsible_No;
       }
       set
       {
          _Responsible_No = value;
       }
    }
    private string _Responsible_No;


    /// <summary>
    /// Applicant number
    /// </summary>
 
    [RfcField(AbapName = "APPLICANT_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 112, Offset2 = 224)]
    [XmlElement("APPLICANT_NO", Form=XmlSchemaForm.Unqualified)]
    public string Applicant_No
    { 
       get
       {
          return _Applicant_No;
       }
       set
       {
          _Applicant_No = value;
       }
    }
    private string _Applicant_No;


    /// <summary>
    /// Company Code
    /// </summary>
 
    [RfcField(AbapName = "COMP_CODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 120, Offset2 = 240)]
    [XmlElement("COMP_CODE", Form=XmlSchemaForm.Unqualified)]
    public string Comp_Code
    { 
       get
       {
          return _Comp_Code;
       }
       set
       {
          _Comp_Code = value;
       }
    }
    private string _Comp_Code;


    /// <summary>
    /// Business Area
    /// </summary>
 
    [RfcField(AbapName = "BUS_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 124, Offset2 = 248)]
    [XmlElement("BUS_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Bus_Area
    { 
       get
       {
          return _Bus_Area;
       }
       set
       {
          _Bus_Area = value;
       }
    }
    private string _Bus_Area;


    /// <summary>
    /// Controlling Area
    /// </summary>
 
    [RfcField(AbapName = "CO_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 128, Offset2 = 256)]
    [XmlElement("CO_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Co_Area
    { 
       get
       {
          return _Co_Area;
       }
       set
       {
          _Co_Area = value;
       }
    }
    private string _Co_Area;


    /// <summary>
    /// Profit Center
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 132, Offset2 = 264)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// Project type
    /// </summary>
 
    [RfcField(AbapName = "PROJ_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 142, Offset2 = 284)]
    [XmlElement("PROJ_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Proj_Type
    { 
       get
       {
          return _Proj_Type;
       }
       set
       {
          _Proj_Type = value;
       }
    }
    private string _Proj_Type;


    /// <summary>
    /// Network assignment
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_ASSIGNMENT", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 144, Offset2 = 288)]
    [XmlElement("NETWORK_ASSIGNMENT", Form=XmlSchemaForm.Unqualified)]
    public string Network_Assignment
    { 
       get
       {
          return _Network_Assignment;
       }
       set
       {
          _Network_Assignment = value;
       }
    }
    private string _Network_Assignment;


    /// <summary>
    /// Costing Sheet
    /// </summary>
 
    [RfcField(AbapName = "COSTING_SHEET", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 145, Offset2 = 290)]
    [XmlElement("COSTING_SHEET", Form=XmlSchemaForm.Unqualified)]
    public string Costing_Sheet
    { 
       get
       {
          return _Costing_Sheet;
       }
       set
       {
          _Costing_Sheet = value;
       }
    }
    private string _Costing_Sheet;


    /// <summary>
    /// Overhead key
    /// </summary>
 
    [RfcField(AbapName = "OVERHEAD_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 151, Offset2 = 302)]
    [XmlElement("OVERHEAD_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Overhead_Key
    { 
       get
       {
          return _Overhead_Key;
       }
       set
       {
          _Overhead_Key = value;
       }
    }
    private string _Overhead_Key;


    /// <summary>
    /// Factory calendar key
    /// </summary>
 
    [RfcField(AbapName = "CALENDAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 157, Offset2 = 314)]
    [XmlElement("CALENDAR", Form=XmlSchemaForm.Unqualified)]
    public string Calendar
    { 
       get
       {
          return _Calendar;
       }
       set
       {
          _Calendar = value;
       }
    }
    private string _Calendar;


    /// <summary>
    /// Priority
    /// </summary>
 
    [RfcField(AbapName = "PRIORITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 159, Offset2 = 318)]
    [XmlElement("PRIORITY", Form=XmlSchemaForm.Unqualified)]
    public string Priority
    { 
       get
       {
          return _Priority;
       }
       set
       {
          _Priority = value;
       }
    }
    private string _Priority;


    /// <summary>
    /// Equipment Number
    /// </summary>
 
    [RfcField(AbapName = "EQUIPMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 160, Offset2 = 320)]
    [XmlElement("EQUIPMENT", Form=XmlSchemaForm.Unqualified)]
    public string Equipment
    { 
       get
       {
          return _Equipment;
       }
       set
       {
          _Equipment = value;
       }
    }
    private string _Equipment;


    /// <summary>
    /// Functional Location
    /// </summary>
 
    [RfcField(AbapName = "FUNCTIONAL_LOCATION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 178, Offset2 = 356)]
    [XmlElement("FUNCTIONAL_LOCATION", Form=XmlSchemaForm.Unqualified)]
    public string Functional_Location
    { 
       get
       {
          return _Functional_Location;
       }
       set
       {
          _Functional_Location = value;
       }
    }
    private string _Functional_Location;


    /// <summary>
    /// Currency Key
    /// </summary>
 
    [RfcField(AbapName = "CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 208, Offset2 = 416)]
    [XmlElement("CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Currency
    { 
       get
       {
          return _Currency;
       }
       set
       {
          _Currency = value;
       }
    }
    private string _Currency;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "CURRENCY_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 213, Offset2 = 426)]
    [XmlElement("CURRENCY_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Currency_Iso
    { 
       get
       {
          return _Currency_Iso;
       }
       set
       {
          _Currency_Iso = value;
       }
    }
    private string _Currency_Iso;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 216, Offset2 = 432)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Key word ID for user-defined fields
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 220, Offset2 = 440)]
    [XmlElement("USER_FIELD_KEY", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Key
    { 
       get
       {
          return _User_Field_Key;
       }
       set
       {
          _User_Field_Key = value;
       }
    }
    private string _User_Field_Key;


    /// <summary>
    /// 1st user field for 20 characters - WBS element-
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR20_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 227, Offset2 = 454)]
    [XmlElement("USER_FIELD_CHAR20_1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char20_1
    { 
       get
       {
          return _User_Field_Char20_1;
       }
       set
       {
          _User_Field_Char20_1 = value;
       }
    }
    private string _User_Field_Char20_1;


    /// <summary>
    /// 2nd user field 20 digits - WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR20_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 247, Offset2 = 494)]
    [XmlElement("USER_FIELD_CHAR20_2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char20_2
    { 
       get
       {
          return _User_Field_Char20_2;
       }
       set
       {
          _User_Field_Char20_2 = value;
       }
    }
    private string _User_Field_Char20_2;


    /// <summary>
    /// 3rd user-defined field 10 digits -WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR10_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 267, Offset2 = 534)]
    [XmlElement("USER_FIELD_CHAR10_1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char10_1
    { 
       get
       {
          return _User_Field_Char10_1;
       }
       set
       {
          _User_Field_Char10_1 = value;
       }
    }
    private string _User_Field_Char10_1;


    /// <summary>
    /// 4th user-defined field 10 digits -WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CHAR10_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 277, Offset2 = 554)]
    [XmlElement("USER_FIELD_CHAR10_2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Char10_2
    { 
       get
       {
          return _User_Field_Char10_2;
       }
       set
       {
          _User_Field_Char10_2 = value;
       }
    }
    private string _User_Field_Char10_2;


    /// <summary>
    /// 1st user-defined field for quantity(length 10,3) WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_QUAN1", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 287, Offset2 = 574)]
    [XmlElement("USER_FIELD_QUAN1", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Quan1
    { 
       get
       {
          return _User_Field_Quan1;
       }
       set
       {
          _User_Field_Quan1 = value;
       }
    }
    private Decimal _User_Field_Quan1;


    /// <summary>
    /// 1st user defined field for quantity field unit - WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 294, Offset2 = 582)]
    [XmlElement("USER_FIELD_UNIT1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit1
    { 
       get
       {
          return _User_Field_Unit1;
       }
       set
       {
          _User_Field_Unit1 = value;
       }
    }
    private string _User_Field_Unit1;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT1_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 297, Offset2 = 588)]
    [XmlElement("USER_FIELD_UNIT1_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit1_Iso
    { 
       get
       {
          return _User_Field_Unit1_Iso;
       }
       set
       {
          _User_Field_Unit1_Iso = value;
       }
    }
    private string _User_Field_Unit1_Iso;


    /// <summary>
    /// 2nd use field for quantity (length 10,3) WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_QUAN2", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 300, Offset2 = 594)]
    [XmlElement("USER_FIELD_QUAN2", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Quan2
    { 
       get
       {
          return _User_Field_Quan2;
       }
       set
       {
          _User_Field_Quan2 = value;
       }
    }
    private Decimal _User_Field_Quan2;


    /// <summary>
    /// 2nd user defined field for quantity field unit - WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 307, Offset2 = 602)]
    [XmlElement("USER_FIELD_UNIT2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit2
    { 
       get
       {
          return _User_Field_Unit2;
       }
       set
       {
          _User_Field_Unit2 = value;
       }
    }
    private string _User_Field_Unit2;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_UNIT2_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 310, Offset2 = 608)]
    [XmlElement("USER_FIELD_UNIT2_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Unit2_Iso
    { 
       get
       {
          return _User_Field_Unit2_Iso;
       }
       set
       {
          _User_Field_Unit2_Iso = value;
       }
    }
    private string _User_Field_Unit2_Iso;


    /// <summary>
    /// 1st user field for values (length 10,3) WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CURR1", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 313, Offset2 = 614)]
    [XmlElement("USER_FIELD_CURR1", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Curr1
    { 
       get
       {
          return _User_Field_Curr1;
       }
       set
       {
          _User_Field_Curr1 = value;
       }
    }
    private Decimal _User_Field_Curr1;


    /// <summary>
    /// 1st user defined field for value field unit - WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 320, Offset2 = 622)]
    [XmlElement("USER_FIELD_CUKY1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky1
    { 
       get
       {
          return _User_Field_Cuky1;
       }
       set
       {
          _User_Field_Cuky1 = value;
       }
    }
    private string _User_Field_Cuky1;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY1_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 325, Offset2 = 632)]
    [XmlElement("USER_FIELD_CUKY1_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky1_Iso
    { 
       get
       {
          return _User_Field_Cuky1_Iso;
       }
       set
       {
          _User_Field_Cuky1_Iso = value;
       }
    }
    private string _User_Field_Cuky1_Iso;


    /// <summary>
    /// 2nd user field for values (length 10,3) -WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CURR2", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 328, Offset2 = 638)]
    [XmlElement("USER_FIELD_CURR2", Form=XmlSchemaForm.Unqualified)]
    public Decimal User_Field_Curr2
    { 
       get
       {
          return _User_Field_Curr2;
       }
       set
       {
          _User_Field_Curr2 = value;
       }
    }
    private Decimal _User_Field_Curr2;


    /// <summary>
    /// 2nd user defined field for value field unit - WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 335, Offset2 = 646)]
    [XmlElement("USER_FIELD_CUKY2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky2
    { 
       get
       {
          return _User_Field_Cuky2;
       }
       set
       {
          _User_Field_Cuky2 = value;
       }
    }
    private string _User_Field_Cuky2;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_CUKY2_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 340, Offset2 = 656)]
    [XmlElement("USER_FIELD_CUKY2_ISO", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Cuky2_Iso
    { 
       get
       {
          return _User_Field_Cuky2_Iso;
       }
       set
       {
          _User_Field_Cuky2_Iso = value;
       }
    }
    private string _User_Field_Cuky2_Iso;


    /// <summary>
    /// 1st user field for date -WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_DATE1", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 343, Offset2 = 662)]
    [XmlElement("USER_FIELD_DATE1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Date1
    { 
       get
       {
          return _User_Field_Date1;
       }
       set
       {
          _User_Field_Date1 = value;
       }
    }
    private string _User_Field_Date1;


    /// <summary>
    /// 2nd user field for date -WBS element
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_DATE2", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 351, Offset2 = 678)]
    [XmlElement("USER_FIELD_DATE2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Date2
    { 
       get
       {
          return _User_Field_Date2;
       }
       set
       {
          _User_Field_Date2 = value;
       }
    }
    private string _User_Field_Date2;


    /// <summary>
    /// 1st user field for 'Ind. for evaluations' WBS elem.
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_FLAG1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 359, Offset2 = 694)]
    [XmlElement("USER_FIELD_FLAG1", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Flag1
    { 
       get
       {
          return _User_Field_Flag1;
       }
       set
       {
          _User_Field_Flag1 = value;
       }
    }
    private string _User_Field_Flag1;


    /// <summary>
    /// 2nd user field for 'Indicator for eval.s' WBS elemnt
    /// </summary>
 
    [RfcField(AbapName = "USER_FIELD_FLAG2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 360, Offset2 = 696)]
    [XmlElement("USER_FIELD_FLAG2", Form=XmlSchemaForm.Unqualified)]
    public string User_Field_Flag2
    { 
       get
       {
          return _User_Field_Flag2;
       }
       set
       {
          _User_Field_Flag2 = value;
       }
    }
    private string _User_Field_Flag2;


    /// <summary>
    /// Object Class
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 361, Offset2 = 698)]
    [XmlElement("OBJECTCLASS", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass
    { 
       get
       {
          return _Objectclass;
       }
       set
       {
          _Objectclass = value;
       }
    }
    private string _Objectclass;


    /// <summary>
    /// Statistical WBS element
    /// </summary>
 
    [RfcField(AbapName = "STATISTICAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 363, Offset2 = 702)]
    [XmlElement("STATISTICAL", Form=XmlSchemaForm.Unqualified)]
    public string Statistical
    { 
       get
       {
          return _Statistical;
       }
       set
       {
          _Statistical = value;
       }
    }
    private string _Statistical;


    /// <summary>
    /// Tax Jurisdiction
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 364, Offset2 = 704)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Interest Profile for Project/Order Interest Calculation
    /// </summary>
 
    [RfcField(AbapName = "INT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 379, Offset2 = 734)]
    [XmlElement("INT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Int_Profile
    { 
       get
       {
          return _Int_Profile;
       }
       set
       {
          _Int_Profile = value;
       }
    }
    private string _Int_Profile;


    /// <summary>
    /// Joint Venture
    /// </summary>
 
    [RfcField(AbapName = "JOINT_VENTURE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 386, Offset2 = 748)]
    [XmlElement("JOINT_VENTURE", Form=XmlSchemaForm.Unqualified)]
    public string Joint_Venture
    { 
       get
       {
          return _Joint_Venture;
       }
       set
       {
          _Joint_Venture = value;
       }
    }
    private string _Joint_Venture;


    /// <summary>
    /// Recovery Indicator
    /// </summary>
 
    [RfcField(AbapName = "RECOVERY_IND", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 392, Offset2 = 760)]
    [XmlElement("RECOVERY_IND", Form=XmlSchemaForm.Unqualified)]
    public string Recovery_Ind
    { 
       get
       {
          return _Recovery_Ind;
       }
       set
       {
          _Recovery_Ind = value;
       }
    }
    private string _Recovery_Ind;


    /// <summary>
    /// Equity type
    /// </summary>
 
    [RfcField(AbapName = "EQUITY_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 394, Offset2 = 764)]
    [XmlElement("EQUITY_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Equity_Type
    { 
       get
       {
          return _Equity_Type;
       }
       set
       {
          _Equity_Type = value;
       }
    }
    private string _Equity_Type;


    /// <summary>
    /// Joint Venture Object Type
    /// </summary>
 
    [RfcField(AbapName = "JV_OBJECT_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 397, Offset2 = 770)]
    [XmlElement("JV_OBJECT_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Object_Type
    { 
       get
       {
          return _Jv_Object_Type;
       }
       set
       {
          _Jv_Object_Type = value;
       }
    }
    private string _Jv_Object_Type;


    /// <summary>
    /// JIB/JIBE Class
    /// </summary>
 
    [RfcField(AbapName = "JV_JIB_CLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 401, Offset2 = 778)]
    [XmlElement("JV_JIB_CLASS", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jib_Class
    { 
       get
       {
          return _Jv_Jib_Class;
       }
       set
       {
          _Jv_Jib_Class = value;
       }
    }
    private string _Jv_Jib_Class;


    /// <summary>
    /// JIB/JIBE Subclass A
    /// </summary>
 
    [RfcField(AbapName = "JV_JIB_SUB_CLASS_A", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 404, Offset2 = 784)]
    [XmlElement("JV_JIB_SUB_CLASS_A", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jib_Sub_Class_A
    { 
       get
       {
          return _Jv_Jib_Sub_Class_A;
       }
       set
       {
          _Jv_Jib_Sub_Class_A = value;
       }
    }
    private string _Jv_Jib_Sub_Class_A;


    /// <summary>
    /// Object class, language-dependent
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 409, Offset2 = 794)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Indicator: Planning element
    /// </summary>
 
    [RfcField(AbapName = "WBS_PLANNING_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 414, Offset2 = 804)]
    [XmlElement("WBS_PLANNING_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Planning_Element
    { 
       get
       {
          return _Wbs_Planning_Element;
       }
       set
       {
          _Wbs_Planning_Element = value;
       }
    }
    private string _Wbs_Planning_Element;


    /// <summary>
    /// Indicator: Account assignment element
    /// </summary>
 
    [RfcField(AbapName = "WBS_ACCOUNT_ASSIGNMENT_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 415, Offset2 = 806)]
    [XmlElement("WBS_ACCOUNT_ASSIGNMENT_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Account_Assignment_Element
    { 
       get
       {
          return _Wbs_Account_Assignment_Element;
       }
       set
       {
          _Wbs_Account_Assignment_Element = value;
       }
    }
    private string _Wbs_Account_Assignment_Element;


    /// <summary>
    /// Indicator: Billing element
    /// </summary>
 
    [RfcField(AbapName = "WBS_BILLING_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 416, Offset2 = 808)]
    [XmlElement("WBS_BILLING_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Billing_Element
    { 
       get
       {
          return _Wbs_Billing_Element;
       }
       set
       {
          _Wbs_Billing_Element = value;
       }
    }
    private string _Wbs_Billing_Element;


    /// <summary>
    /// Responsible cost center
    /// </summary>
 
    [RfcField(AbapName = "RESPSBL_CCTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 417, Offset2 = 810)]
    [XmlElement("RESPSBL_CCTR", Form=XmlSchemaForm.Unqualified)]
    public string Respsbl_Cctr
    { 
       get
       {
          return _Respsbl_Cctr;
       }
       set
       {
          _Respsbl_Cctr = value;
       }
    }
    private string _Respsbl_Cctr;


    /// <summary>
    /// Controlling area of responsible cost center
    /// </summary>
 
    [RfcField(AbapName = "RESPSBL_CCTR_CONTROLLING_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 427, Offset2 = 830)]
    [XmlElement("RESPSBL_CCTR_CONTROLLING_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Respsbl_Cctr_Controlling_Area
    { 
       get
       {
          return _Respsbl_Cctr_Controlling_Area;
       }
       set
       {
          _Respsbl_Cctr_Controlling_Area = value;
       }
    }
    private string _Respsbl_Cctr_Controlling_Area;


    /// <summary>
    /// Requesting cost center
    /// </summary>
 
    [RfcField(AbapName = "REQUEST_CCTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 431, Offset2 = 838)]
    [XmlElement("REQUEST_CCTR", Form=XmlSchemaForm.Unqualified)]
    public string Request_Cctr
    { 
       get
       {
          return _Request_Cctr;
       }
       set
       {
          _Request_Cctr = value;
       }
    }
    private string _Request_Cctr;


    /// <summary>
    /// Requesting company code
    /// </summary>
 
    [RfcField(AbapName = "REQUEST_COMP_CODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 441, Offset2 = 858)]
    [XmlElement("REQUEST_COMP_CODE", Form=XmlSchemaForm.Unqualified)]
    public string Request_Comp_Code
    { 
       get
       {
          return _Request_Comp_Code;
       }
       set
       {
          _Request_Comp_Code = value;
       }
    }
    private string _Request_Comp_Code;


    /// <summary>
    /// Controlling area of requesting cost center
    /// </summary>
 
    [RfcField(AbapName = "REQUEST_CCTR_CONTROLLING_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 445, Offset2 = 866)]
    [XmlElement("REQUEST_CCTR_CONTROLLING_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Request_Cctr_Controlling_Area
    { 
       get
       {
          return _Request_Cctr_Controlling_Area;
       }
       set
       {
          _Request_Cctr_Controlling_Area = value;
       }
    }
    private string _Request_Cctr_Controlling_Area;


    /// <summary>
    /// Location
    /// </summary>
 
    [RfcField(AbapName = "LOCATION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 449, Offset2 = 874)]
    [XmlElement("LOCATION", Form=XmlSchemaForm.Unqualified)]
    public string Location
    { 
       get
       {
          return _Location;
       }
       set
       {
          _Location = value;
       }
    }
    private string _Location;


    /// <summary>
    /// Change Number
    /// </summary>
 
    [RfcField(AbapName = "CHANGE_NO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 459, Offset2 = 894)]
    [XmlElement("CHANGE_NO", Form=XmlSchemaForm.Unqualified)]
    public string Change_No
    { 
       get
       {
          return _Change_No;
       }
       set
       {
          _Change_No = value;
       }
    }
    private string _Change_No;


    /// <summary>
    /// Investment measure profile
    /// </summary>
 
    [RfcField(AbapName = "INVEST_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 471, Offset2 = 918)]
    [XmlElement("INVEST_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Invest_Profile
    { 
       get
       {
          return _Invest_Profile;
       }
       set
       {
          _Invest_Profile = value;
       }
    }
    private string _Invest_Profile;


    /// <summary>
    /// Results Analysis Key
    /// </summary>
 
    [RfcField(AbapName = "RES_ANAL_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 477, Offset2 = 930)]
    [XmlElement("RES_ANAL_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Res_Anal_Key
    { 
       get
       {
          return _Res_Anal_Key;
       }
       set
       {
          _Res_Anal_Key = value;
       }
    }
    private string _Res_Anal_Key;


    /// <summary>
    /// Cost center to which costs are actually posted
    /// </summary>
 
    [RfcField(AbapName = "WBS_CCTR_POSTED_ACTUAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 483, Offset2 = 942)]
    [XmlElement("WBS_CCTR_POSTED_ACTUAL", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Cctr_Posted_Actual
    { 
       get
       {
          return _Wbs_Cctr_Posted_Actual;
       }
       set
       {
          _Wbs_Cctr_Posted_Actual = value;
       }
    }
    private string _Wbs_Cctr_Posted_Actual;


    /// <summary>
    /// WBS element: Basic start date
    /// </summary>
 
    [RfcField(AbapName = "WBS_BASIC_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 493, Offset2 = 962)]
    [XmlElement("WBS_BASIC_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Basic_Start_Date
    { 
       get
       {
          return _Wbs_Basic_Start_Date;
       }
       set
       {
          _Wbs_Basic_Start_Date = value;
       }
    }
    private string _Wbs_Basic_Start_Date;


    /// <summary>
    /// WBS element: Basic finish date
    /// </summary>
 
    [RfcField(AbapName = "WBS_BASIC_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 501, Offset2 = 978)]
    [XmlElement("WBS_BASIC_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Basic_Finish_Date
    { 
       get
       {
          return _Wbs_Basic_Finish_Date;
       }
       set
       {
          _Wbs_Basic_Finish_Date = value;
       }
    }
    private string _Wbs_Basic_Finish_Date;


    /// <summary>
    /// Forecasted start date of the WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_FORECAST_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 509, Offset2 = 994)]
    [XmlElement("WBS_FORECAST_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Forecast_Start_Date
    { 
       get
       {
          return _Wbs_Forecast_Start_Date;
       }
       set
       {
          _Wbs_Forecast_Start_Date = value;
       }
    }
    private string _Wbs_Forecast_Start_Date;


    /// <summary>
    /// Forecasted finish date of the WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_FORECAST_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 517, Offset2 = 1010)]
    [XmlElement("WBS_FORECAST_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Forecast_Finish_Date
    { 
       get
       {
          return _Wbs_Forecast_Finish_Date;
       }
       set
       {
          _Wbs_Forecast_Finish_Date = value;
       }
    }
    private string _Wbs_Forecast_Finish_Date;


    /// <summary>
    /// Actual start date for the WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_ACTUAL_START_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 525, Offset2 = 1026)]
    [XmlElement("WBS_ACTUAL_START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Actual_Start_Date
    { 
       get
       {
          return _Wbs_Actual_Start_Date;
       }
       set
       {
          _Wbs_Actual_Start_Date = value;
       }
    }
    private string _Wbs_Actual_Start_Date;


    /// <summary>
    /// Actual finish date of the WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_ACTUAL_FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 533, Offset2 = 1042)]
    [XmlElement("WBS_ACTUAL_FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Actual_Finish_Date
    { 
       get
       {
          return _Wbs_Actual_Finish_Date;
       }
       set
       {
          _Wbs_Actual_Finish_Date = value;
       }
    }
    private string _Wbs_Actual_Finish_Date;


    /// <summary>
    /// Length (duration) of the basic dates in the WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_BASIC_DURATION", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Decimals = 1, Offset = 541, Offset2 = 1058)]
    [XmlElement("WBS_BASIC_DURATION", Form=XmlSchemaForm.Unqualified)]
    public Decimal Wbs_Basic_Duration
    { 
       get
       {
          return _Wbs_Basic_Duration;
       }
       set
       {
          _Wbs_Basic_Duration = value;
       }
    }
    private Decimal _Wbs_Basic_Duration;


    /// <summary>
    /// Unit for duration of basic WBS element dates
    /// </summary>
 
    [RfcField(AbapName = "WBS_BASIC_DUR_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 544, Offset2 = 1062)]
    [XmlElement("WBS_BASIC_DUR_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Basic_Dur_Unit
    { 
       get
       {
          return _Wbs_Basic_Dur_Unit;
       }
       set
       {
          _Wbs_Basic_Dur_Unit = value;
       }
    }
    private string _Wbs_Basic_Dur_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "WBS_BASIC_DUR_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 547, Offset2 = 1068)]
    [XmlElement("WBS_BASIC_DUR_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Basic_Dur_Unit_Iso
    { 
       get
       {
          return _Wbs_Basic_Dur_Unit_Iso;
       }
       set
       {
          _Wbs_Basic_Dur_Unit_Iso = value;
       }
    }
    private string _Wbs_Basic_Dur_Unit_Iso;


    /// <summary>
    /// Forecasted length (duration) of the WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_FORECAST_DURATION", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Decimals = 1, Offset = 550, Offset2 = 1074)]
    [XmlElement("WBS_FORECAST_DURATION", Form=XmlSchemaForm.Unqualified)]
    public Decimal Wbs_Forecast_Duration
    { 
       get
       {
          return _Wbs_Forecast_Duration;
       }
       set
       {
          _Wbs_Forecast_Duration = value;
       }
    }
    private Decimal _Wbs_Forecast_Duration;


    /// <summary>
    /// Unit for duration of WBS element planned dates
    /// </summary>
 
    [RfcField(AbapName = "WBS_FORCAST_DUR_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 553, Offset2 = 1078)]
    [XmlElement("WBS_FORCAST_DUR_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Forcast_Dur_Unit
    { 
       get
       {
          return _Wbs_Forcast_Dur_Unit;
       }
       set
       {
          _Wbs_Forcast_Dur_Unit = value;
       }
    }
    private string _Wbs_Forcast_Dur_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "WBS_FORECAST_DUR_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 556, Offset2 = 1084)]
    [XmlElement("WBS_FORECAST_DUR_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Forecast_Dur_Unit_Iso
    { 
       get
       {
          return _Wbs_Forecast_Dur_Unit_Iso;
       }
       set
       {
          _Wbs_Forecast_Dur_Unit_Iso = value;
       }
    }
    private string _Wbs_Forecast_Dur_Unit_Iso;


    /// <summary>
    /// Actual length (duration) of the WBS element
    /// </summary>
 
    [RfcField(AbapName = "WBS_ACTUAL_DURATION", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Decimals = 1, Offset = 559, Offset2 = 1090)]
    [XmlElement("WBS_ACTUAL_DURATION", Form=XmlSchemaForm.Unqualified)]
    public Decimal Wbs_Actual_Duration
    { 
       get
       {
          return _Wbs_Actual_Duration;
       }
       set
       {
          _Wbs_Actual_Duration = value;
       }
    }
    private Decimal _Wbs_Actual_Duration;


    /// <summary>
    /// Unit for duration of actual WBS element dates
    /// </summary>
 
    [RfcField(AbapName = "WBS_ACTUAL_DUR_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 562, Offset2 = 1094)]
    [XmlElement("WBS_ACTUAL_DUR_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Actual_Dur_Unit
    { 
       get
       {
          return _Wbs_Actual_Dur_Unit;
       }
       set
       {
          _Wbs_Actual_Dur_Unit = value;
       }
    }
    private string _Wbs_Actual_Dur_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "WBS_ACTUAL_DUR_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 565, Offset2 = 1100)]
    [XmlElement("WBS_ACTUAL_DUR_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Actual_Dur_Unit_Iso
    { 
       get
       {
          return _Wbs_Actual_Dur_Unit_Iso;
       }
       set
       {
          _Wbs_Actual_Dur_Unit_Iso = value;
       }
    }
    private string _Wbs_Actual_Dur_Unit_Iso;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 568, Offset2 = 1106)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 572, Offset2 = 1114)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;

  }

}
