
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Network header BAPI structure update
  /// </summary>
  [RfcStructure(AbapName ="BAPI_NETWORK_UPDATE" , Length = 28, Length2 = 56)]
  [Serializable]
  public class BAPI_NETWORK_UPDATE : SAPStructure
  {
   

    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Network
    { 
       get
       {
          return _Network;
       }
       set
       {
          _Network = value;
       }
    }
    private string _Network;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 1, Offset2 = 2)]
    [XmlElement("NETWORK_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Network_Type
    { 
       get
       {
          return _Network_Type;
       }
       set
       {
          _Network_Type = value;
       }
    }
    private string _Network_Type;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SHORT_TEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 2, Offset2 = 4)]
    [XmlElement("SHORT_TEXT", Form=XmlSchemaForm.Unqualified)]
    public string Short_Text
    { 
       get
       {
          return _Short_Text;
       }
       set
       {
          _Short_Text = value;
       }
    }
    private string _Short_Text;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 3, Offset2 = 6)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 4, Offset2 = 8)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "WBS_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 5, Offset2 = 10)]
    [XmlElement("WBS_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Element
    { 
       get
       {
          return _Wbs_Element;
       }
       set
       {
          _Wbs_Element = value;
       }
    }
    private string _Wbs_Element;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 6, Offset2 = 12)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 7, Offset2 = 14)]
    [XmlElement("OBJECTCLASS", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass
    { 
       get
       {
          return _Objectclass;
       }
       set
       {
          _Objectclass = value;
       }
    }
    private string _Objectclass;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SD_DOC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 8, Offset2 = 16)]
    [XmlElement("SD_DOC", Form=XmlSchemaForm.Unqualified)]
    public string Sd_Doc
    { 
       get
       {
          return _Sd_Doc;
       }
       set
       {
          _Sd_Doc = value;
       }
    }
    private string _Sd_Doc;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ITM_NUMBER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 9, Offset2 = 18)]
    [XmlElement("ITM_NUMBER", Form=XmlSchemaForm.Unqualified)]
    public string Itm_Number
    { 
       get
       {
          return _Itm_Number;
       }
       set
       {
          _Itm_Number = value;
       }
    }
    private string _Itm_Number;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FINISH_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 10, Offset2 = 20)]
    [XmlElement("FINISH_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Finish_Date
    { 
       get
       {
          return _Finish_Date;
       }
       set
       {
          _Finish_Date = value;
       }
    }
    private string _Finish_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "START_DATE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 11, Offset2 = 22)]
    [XmlElement("START_DATE", Form=XmlSchemaForm.Unqualified)]
    public string Start_Date
    { 
       get
       {
          return _Start_Date;
       }
       set
       {
          _Start_Date = value;
       }
    }
    private string _Start_Date;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "MRP_CONTROLLER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 12, Offset2 = 24)]
    [XmlElement("MRP_CONTROLLER", Form=XmlSchemaForm.Unqualified)]
    public string Mrp_Controller
    { 
       get
       {
          return _Mrp_Controller;
       }
       set
       {
          _Mrp_Controller = value;
       }
    }
    private string _Mrp_Controller;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SCHED_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 13, Offset2 = 26)]
    [XmlElement("SCHED_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Type
    { 
       get
       {
          return _Sched_Type;
       }
       set
       {
          _Sched_Type = value;
       }
    }
    private string _Sched_Type;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PRIORITY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 14, Offset2 = 28)]
    [XmlElement("PRIORITY", Form=XmlSchemaForm.Unqualified)]
    public string Priority
    { 
       get
       {
          return _Priority;
       }
       set
       {
          _Priority = value;
       }
    }
    private string _Priority;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 15, Offset2 = 30)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NOT_AUTO_SCHEDULE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 16, Offset2 = 32)]
    [XmlElement("NOT_AUTO_SCHEDULE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Auto_Schedule
    { 
       get
       {
          return _Not_Auto_Schedule;
       }
       set
       {
          _Not_Auto_Schedule = value;
       }
    }
    private string _Not_Auto_Schedule;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NOT_AUTO_COSTING", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 17, Offset2 = 34)]
    [XmlElement("NOT_AUTO_COSTING", Form=XmlSchemaForm.Unqualified)]
    public string Not_Auto_Costing
    { 
       get
       {
          return _Not_Auto_Costing;
       }
       set
       {
          _Not_Auto_Costing = value;
       }
    }
    private string _Not_Auto_Costing;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SUPERIOR_NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 18, Offset2 = 36)]
    [XmlElement("SUPERIOR_NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Superior_Network
    { 
       get
       {
          return _Superior_Network;
       }
       set
       {
          _Superior_Network = value;
       }
    }
    private string _Superior_Network;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_OF_SUP_NETWORK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 19, Offset2 = 38)]
    [XmlElement("ACTIVITY_OF_SUP_NETWORK", Form=XmlSchemaForm.Unqualified)]
    public string Activity_Of_Sup_Network
    { 
       get
       {
          return _Activity_Of_Sup_Network;
       }
       set
       {
          _Activity_Of_Sup_Network = value;
       }
    }
    private string _Activity_Of_Sup_Network;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NOT_MRP_APPLICABLE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 20, Offset2 = 40)]
    [XmlElement("NOT_MRP_APPLICABLE", Form=XmlSchemaForm.Unqualified)]
    public string Not_Mrp_Applicable
    { 
       get
       {
          return _Not_Mrp_Applicable;
       }
       set
       {
          _Not_Mrp_Applicable = value;
       }
    }
    private string _Not_Mrp_Applicable;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 21, Offset2 = 42)]
    [XmlElement("PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Profile
    { 
       get
       {
          return _Profile;
       }
       set
       {
          _Profile = value;
       }
    }
    private string _Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FINISH_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 22, Offset2 = 44)]
    [XmlElement("FINISH_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Finish_Date_Forecast
    { 
       get
       {
          return _Finish_Date_Forecast;
       }
       set
       {
          _Finish_Date_Forecast = value;
       }
    }
    private string _Finish_Date_Forecast;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "START_DATE_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 23, Offset2 = 46)]
    [XmlElement("START_DATE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Start_Date_Forecast
    { 
       get
       {
          return _Start_Date_Forecast;
       }
       set
       {
          _Start_Date_Forecast = value;
       }
    }
    private string _Start_Date_Forecast;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "SCHED_TYPE_FORECAST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 24, Offset2 = 48)]
    [XmlElement("SCHED_TYPE_FORECAST", Form=XmlSchemaForm.Unqualified)]
    public string Sched_Type_Forecast
    { 
       get
       {
          return _Sched_Type_Forecast;
       }
       set
       {
          _Sched_Type_Forecast = value;
       }
    }
    private string _Sched_Type_Forecast;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 25, Offset2 = 50)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 26, Offset2 = 52)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 27, Offset2 = 54)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;

  }

}
