
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Project Definition and Description
  /// </summary>
  [RfcStructure(AbapName ="BAPIPREXP" , Length = 64, Length2 = 128)]
  [Serializable]
  public class BAPIPREXP : SAPStructure
  {
   

    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 0, Offset2 = 0)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// PS: Short description (1st text line)
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 24, Offset2 = 48)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;

  }

}
