
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI Interface Structure for Ranges of Project Definitions
  /// </summary>
  [RfcStructure(AbapName ="BAPI_2002_PD_RANGE" , Length = 51, Length2 = 102)]
  [Serializable]
  public class BAPI_2002_PD_RANGE : SAPStructure
  {
   

    /// <summary>
    /// Inclusion/exclusion criterion SIGN for range tables
    /// </summary>
 
    [RfcField(AbapName = "SIGN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("SIGN", Form=XmlSchemaForm.Unqualified)]
    public string Sign
    { 
       get
       {
          return _Sign;
       }
       set
       {
          _Sign = value;
       }
    }
    private string _Sign;


    /// <summary>
    /// Selection operator OPTION for range tables
    /// </summary>
 
    [RfcField(AbapName = "OPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 1, Offset2 = 2)]
    [XmlElement("OPTION", Form=XmlSchemaForm.Unqualified)]
    public string Option0
    { 
       get
       {
          return _Option0;
       }
       set
       {
          _Option0 = value;
       }
    }
    private string _Option0;


    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "LOW", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 3, Offset2 = 6)]
    [XmlElement("LOW", Form=XmlSchemaForm.Unqualified)]
    public string Low
    { 
       get
       {
          return _Low;
       }
       set
       {
          _Low = value;
       }
    }
    private string _Low;


    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "HIGH", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 27, Offset2 = 54)]
    [XmlElement("HIGH", Form=XmlSchemaForm.Unqualified)]
    public string High
    { 
       get
       {
          return _High;
       }
       set
       {
          _High = value;
       }
    }
    private string _High;

  }

}
