
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Message table for BAPIs (Project System)
  /// </summary>
  [RfcStructure(AbapName ="BAPI_METH_MESSAGE" , Length = 340, Length2 = 680)]
  [Serializable]
  public class BAPI_METH_MESSAGE : SAPStructure
  {
   

    /// <summary>
    /// Method
    /// </summary>
 
    [RfcField(AbapName = "METHOD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 32, Length2 = 64, Offset = 0, Offset2 = 0)]
    [XmlElement("METHOD", Form=XmlSchemaForm.Unqualified)]
    public string Method
    { 
       get
       {
          return _Method;
       }
       set
       {
          _Method = value;
       }
    }
    private string _Method;


    /// <summary>
    /// Object type
    /// </summary>
 
    [RfcField(AbapName = "OBJECT_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 32, Length2 = 64, Offset = 32, Offset2 = 64)]
    [XmlElement("OBJECT_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Object_Type
    { 
       get
       {
          return _Object_Type;
       }
       set
       {
          _Object_Type = value;
       }
    }
    private string _Object_Type;


    /// <summary>
    /// SAP internal object key
    /// </summary>
 
    [RfcField(AbapName = "INTERNAL_OBJECT_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 90, Length2 = 180, Offset = 64, Offset2 = 128)]
    [XmlElement("INTERNAL_OBJECT_ID", Form=XmlSchemaForm.Unqualified)]
    public string Internal_Object_Id
    { 
       get
       {
          return _Internal_Object_Id;
       }
       set
       {
          _Internal_Object_Id = value;
       }
    }
    private string _Internal_Object_Id;


    /// <summary>
    /// SAP external object key
    /// </summary>
 
    [RfcField(AbapName = "EXTERNAL_OBJECT_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 90, Length2 = 180, Offset = 154, Offset2 = 308)]
    [XmlElement("EXTERNAL_OBJECT_ID", Form=XmlSchemaForm.Unqualified)]
    public string External_Object_Id
    { 
       get
       {
          return _External_Object_Id;
       }
       set
       {
          _External_Object_Id = value;
       }
    }
    private string _External_Object_Id;


    /// <summary>
    /// Message Identification
    /// </summary>
 
    [RfcField(AbapName = "MESSAGE_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 244, Offset2 = 488)]
    [XmlElement("MESSAGE_ID", Form=XmlSchemaForm.Unqualified)]
    public string Message_Id
    { 
       get
       {
          return _Message_Id;
       }
       set
       {
          _Message_Id = value;
       }
    }
    private string _Message_Id;


    /// <summary>
    /// System Message Number
    /// </summary>
 
    [RfcField(AbapName = "MESSAGE_NUMBER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 264, Offset2 = 528)]
    [XmlElement("MESSAGE_NUMBER", Form=XmlSchemaForm.Unqualified)]
    public string Message_Number
    { 
       get
       {
          return _Message_Number;
       }
       set
       {
          _Message_Number = value;
       }
    }
    private string _Message_Number;


    /// <summary>
    /// Message Type
    /// </summary>
 
    [RfcField(AbapName = "MESSAGE_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 267, Offset2 = 534)]
    [XmlElement("MESSAGE_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Message_Type
    { 
       get
       {
          return _Message_Type;
       }
       set
       {
          _Message_Type = value;
       }
    }
    private string _Message_Type;


    /// <summary>
    /// Text Line of a Message
    /// </summary>
 
    [RfcField(AbapName = "MESSAGE_TEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 72, Length2 = 144, Offset = 268, Offset2 = 536)]
    [XmlElement("MESSAGE_TEXT", Form=XmlSchemaForm.Unqualified)]
    public string Message_Text
    { 
       get
       {
          return _Message_Text;
       }
       set
       {
          _Message_Text = value;
       }
    }
    private string _Message_Text;

  }

}
