
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI transfer structure: WBS hierarchy
  /// </summary>
  [RfcStructure(AbapName ="BAPI_WBS_HIERARCHIE" , Length = 144, Length2 = 288)]
  [Serializable]
  public class BAPI_WBS_HIERARCHIE : SAPStructure
  {
   

    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "WBS_ELEMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 0, Offset2 = 0)]
    [XmlElement("WBS_ELEMENT", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Element
    { 
       get
       {
          return _Wbs_Element;
       }
       set
       {
          _Wbs_Element = value;
       }
    }
    private string _Wbs_Element;


    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 24, Offset2 = 48)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "UP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 48, Offset2 = 96)]
    [XmlElement("UP", Form=XmlSchemaForm.Unqualified)]
    public string Up
    { 
       get
       {
          return _Up;
       }
       set
       {
          _Up = value;
       }
    }
    private string _Up;


    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "DOWN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 72, Offset2 = 144)]
    [XmlElement("DOWN", Form=XmlSchemaForm.Unqualified)]
    public string Down
    { 
       get
       {
          return _Down;
       }
       set
       {
          _Down = value;
       }
    }
    private string _Down;


    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "LEFT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 96, Offset2 = 192)]
    [XmlElement("LEFT", Form=XmlSchemaForm.Unqualified)]
    public string Left
    { 
       get
       {
          return _Left;
       }
       set
       {
          _Left = value;
       }
    }
    private string _Left;


    /// <summary>
    /// Work Breakdown Structure Element (WBS Element)
    /// </summary>
 
    [RfcField(AbapName = "RIGHT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 120, Offset2 = 240)]
    [XmlElement("RIGHT", Form=XmlSchemaForm.Unqualified)]
    public string Right
    { 
       get
       {
          return _Right;
       }
       set
       {
          _Right = value;
       }
    }
    private string _Right;

  }

}
