
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// Project definition BAPI structure (Export)
  /// </summary>
  [RfcStructure(AbapName ="BAPI_PROJECT_DEFINITION_EX" , Length = 284, Length2 = 568)]
  [Serializable]
  public class BAPI_PROJECT_DEFINITION_EX : SAPStructure
  {
   

    /// <summary>
    /// Project Definition
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 0, Offset2 = 0)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// PS: Short description (1st text line)
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 24, Offset2 = 48)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;


    /// <summary>
    /// Selection mask for WBS element short IDs
    /// </summary>
 
    [RfcField(AbapName = "MASK_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 24, Length2 = 48, Offset = 64, Offset2 = 128)]
    [XmlElement("MASK_ID", Form=XmlSchemaForm.Unqualified)]
    public string Mask_Id
    { 
       get
       {
          return _Mask_Id;
       }
       set
       {
          _Mask_Id = value;
       }
    }
    private string _Mask_Id;


    /// <summary>
    /// Number of the responsible person (project manager)
    /// </summary>
 
    [RfcField(AbapName = "RESPONSIBLE_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 88, Offset2 = 176)]
    [XmlElement("RESPONSIBLE_NO", Form=XmlSchemaForm.Unqualified)]
    public string Responsible_No
    { 
       get
       {
          return _Responsible_No;
       }
       set
       {
          _Responsible_No = value;
       }
    }
    private string _Responsible_No;


    /// <summary>
    /// Applicant number
    /// </summary>
 
    [RfcField(AbapName = "APPLICANT_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 96, Offset2 = 192)]
    [XmlElement("APPLICANT_NO", Form=XmlSchemaForm.Unqualified)]
    public string Applicant_No
    { 
       get
       {
          return _Applicant_No;
       }
       set
       {
          _Applicant_No = value;
       }
    }
    private string _Applicant_No;


    /// <summary>
    /// Company Code
    /// </summary>
 
    [RfcField(AbapName = "COMP_CODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 104, Offset2 = 208)]
    [XmlElement("COMP_CODE", Form=XmlSchemaForm.Unqualified)]
    public string Comp_Code
    { 
       get
       {
          return _Comp_Code;
       }
       set
       {
          _Comp_Code = value;
       }
    }
    private string _Comp_Code;


    /// <summary>
    /// Business Area
    /// </summary>
 
    [RfcField(AbapName = "BUS_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 108, Offset2 = 216)]
    [XmlElement("BUS_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Bus_Area
    { 
       get
       {
          return _Bus_Area;
       }
       set
       {
          _Bus_Area = value;
       }
    }
    private string _Bus_Area;


    /// <summary>
    /// Controlling Area
    /// </summary>
 
    [RfcField(AbapName = "CONTROLLING_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 112, Offset2 = 224)]
    [XmlElement("CONTROLLING_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Controlling_Area
    { 
       get
       {
          return _Controlling_Area;
       }
       set
       {
          _Controlling_Area = value;
       }
    }
    private string _Controlling_Area;


    /// <summary>
    /// Profit Center
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 116, Offset2 = 232)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// WBS currency (project definition)
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 126, Offset2 = 252)]
    [XmlElement("PROJECT_CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Project_Currency
    { 
       get
       {
          return _Project_Currency;
       }
       set
       {
          _Project_Currency = value;
       }
    }
    private string _Project_Currency;


    /// <summary>
    /// ISO currency code
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_CURRENCY_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 131, Offset2 = 262)]
    [XmlElement("PROJECT_CURRENCY_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Project_Currency_Iso
    { 
       get
       {
          return _Project_Currency_Iso;
       }
       set
       {
          _Project_Currency_Iso = value;
       }
    }
    private string _Project_Currency_Iso;


    /// <summary>
    /// Network assignment
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_ASSIGNMENT", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 134, Offset2 = 268)]
    [XmlElement("NETWORK_ASSIGNMENT", Form=XmlSchemaForm.Unqualified)]
    public string Network_Assignment
    { 
       get
       {
          return _Network_Assignment;
       }
       set
       {
          _Network_Assignment = value;
       }
    }
    private string _Network_Assignment;


    /// <summary>
    /// Project planned start date
    /// </summary>
 
    [RfcField(AbapName = "START", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 135, Offset2 = 270)]
    [XmlElement("START", Form=XmlSchemaForm.Unqualified)]
    public string Start
    { 
       get
       {
          return _Start;
       }
       set
       {
          _Start = value;
       }
    }
    private string _Start;


    /// <summary>
    /// Project planned finish date
    /// </summary>
 
    [RfcField(AbapName = "FINISH", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 143, Offset2 = 286)]
    [XmlElement("FINISH", Form=XmlSchemaForm.Unqualified)]
    public string Finish
    { 
       get
       {
          return _Finish;
       }
       set
       {
          _Finish = value;
       }
    }
    private string _Finish;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 151, Offset2 = 302)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Factory calendar key
    /// </summary>
 
    [RfcField(AbapName = "CALENDAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 155, Offset2 = 310)]
    [XmlElement("CALENDAR", Form=XmlSchemaForm.Unqualified)]
    public string Calendar
    { 
       get
       {
          return _Calendar;
       }
       set
       {
          _Calendar = value;
       }
    }
    private string _Calendar;


    /// <summary>
    /// Planning method for project basic dates
    /// </summary>
 
    [RfcField(AbapName = "PLAN_BASIC", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 157, Offset2 = 314)]
    [XmlElement("PLAN_BASIC", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Basic
    { 
       get
       {
          return _Plan_Basic;
       }
       set
       {
          _Plan_Basic = value;
       }
    }
    private string _Plan_Basic;


    /// <summary>
    /// Planning method for project forecast dates
    /// </summary>
 
    [RfcField(AbapName = "PLAN_FCST", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 158, Offset2 = 316)]
    [XmlElement("PLAN_FCST", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Fcst
    { 
       get
       {
          return _Plan_Fcst;
       }
       set
       {
          _Plan_Fcst = value;
       }
    }
    private string _Plan_Fcst;


    /// <summary>
    /// Time unit in time scheduling
    /// </summary>
 
    [RfcField(AbapName = "TIME_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 159, Offset2 = 318)]
    [XmlElement("TIME_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Time_Unit
    { 
       get
       {
          return _Time_Unit;
       }
       set
       {
          _Time_Unit = value;
       }
    }
    private string _Time_Unit;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "TIME_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 162, Offset2 = 324)]
    [XmlElement("TIME_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Time_Unit_Iso
    { 
       get
       {
          return _Time_Unit_Iso;
       }
       set
       {
          _Time_Unit_Iso = value;
       }
    }
    private string _Time_Unit_Iso;


    /// <summary>
    /// Network profile
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 165, Offset2 = 330)]
    [XmlElement("NETWORK_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Network_Profile
    { 
       get
       {
          return _Network_Profile;
       }
       set
       {
          _Network_Profile = value;
       }
    }
    private string _Network_Profile;


    /// <summary>
    /// Project Profile
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 172, Offset2 = 344)]
    [XmlElement("PROJECT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Project_Profile
    { 
       get
       {
          return _Project_Profile;
       }
       set
       {
          _Project_Profile = value;
       }
    }
    private string _Project_Profile;


    /// <summary>
    /// Budget Profile
    /// </summary>
 
    [RfcField(AbapName = "BUDGET_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 179, Offset2 = 358)]
    [XmlElement("BUDGET_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Budget_Profile
    { 
       get
       {
          return _Budget_Profile;
       }
       set
       {
          _Budget_Profile = value;
       }
    }
    private string _Budget_Profile;


    /// <summary>
    /// Project stock
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_STOCK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 185, Offset2 = 370)]
    [XmlElement("PROJECT_STOCK", Form=XmlSchemaForm.Unqualified)]
    public string Project_Stock
    { 
       get
       {
          return _Project_Stock;
       }
       set
       {
          _Project_Stock = value;
       }
    }
    private string _Project_Stock;


    /// <summary>
    /// Object Class
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 186, Offset2 = 372)]
    [XmlElement("OBJECTCLASS", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass
    { 
       get
       {
          return _Objectclass;
       }
       set
       {
          _Objectclass = value;
       }
    }
    private string _Objectclass;


    /// <summary>
    /// Statistical WBS element
    /// </summary>
 
    [RfcField(AbapName = "STATISTICAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 188, Offset2 = 376)]
    [XmlElement("STATISTICAL", Form=XmlSchemaForm.Unqualified)]
    public string Statistical
    { 
       get
       {
          return _Statistical;
       }
       set
       {
          _Statistical = value;
       }
    }
    private string _Statistical;


    /// <summary>
    /// Tax Jurisdiction
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 189, Offset2 = 378)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Interest Profile for Project/Order Interest Calculation
    /// </summary>
 
    [RfcField(AbapName = "INT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 7, Length2 = 14, Offset = 204, Offset2 = 408)]
    [XmlElement("INT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Int_Profile
    { 
       get
       {
          return _Int_Profile;
       }
       set
       {
          _Int_Profile = value;
       }
    }
    private string _Int_Profile;


    /// <summary>
    /// Profile for WBS scheduling
    /// </summary>
 
    [RfcField(AbapName = "WBS_SCHED_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 211, Offset2 = 422)]
    [XmlElement("WBS_SCHED_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Sched_Profile
    { 
       get
       {
          return _Wbs_Sched_Profile;
       }
       set
       {
          _Wbs_Sched_Profile = value;
       }
    }
    private string _Wbs_Sched_Profile;


    /// <summary>
    /// Payment plan profile
    /// </summary>
 
    [RfcField(AbapName = "CSH_BDGT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 223, Offset2 = 446)]
    [XmlElement("CSH_BDGT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Csh_Bdgt_Profile
    { 
       get
       {
          return _Csh_Bdgt_Profile;
       }
       set
       {
          _Csh_Bdgt_Profile = value;
       }
    }
    private string _Csh_Bdgt_Profile;


    /// <summary>
    /// Planning profile
    /// </summary>
 
    [RfcField(AbapName = "PLAN_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 229, Offset2 = 458)]
    [XmlElement("PLAN_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Profile
    { 
       get
       {
          return _Plan_Profile;
       }
       set
       {
          _Plan_Profile = value;
       }
    }
    private string _Plan_Profile;


    /// <summary>
    /// Joint Venture
    /// </summary>
 
    [RfcField(AbapName = "JOINT_VENTURE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 235, Offset2 = 470)]
    [XmlElement("JOINT_VENTURE", Form=XmlSchemaForm.Unqualified)]
    public string Joint_Venture
    { 
       get
       {
          return _Joint_Venture;
       }
       set
       {
          _Joint_Venture = value;
       }
    }
    private string _Joint_Venture;


    /// <summary>
    /// Recovery Indicator
    /// </summary>
 
    [RfcField(AbapName = "RECOVERY_IND", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 241, Offset2 = 482)]
    [XmlElement("RECOVERY_IND", Form=XmlSchemaForm.Unqualified)]
    public string Recovery_Ind
    { 
       get
       {
          return _Recovery_Ind;
       }
       set
       {
          _Recovery_Ind = value;
       }
    }
    private string _Recovery_Ind;


    /// <summary>
    /// Equity type
    /// </summary>
 
    [RfcField(AbapName = "EQUITY_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 243, Offset2 = 486)]
    [XmlElement("EQUITY_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Equity_Type
    { 
       get
       {
          return _Equity_Type;
       }
       set
       {
          _Equity_Type = value;
       }
    }
    private string _Equity_Type;


    /// <summary>
    /// Joint Venture Object Type
    /// </summary>
 
    [RfcField(AbapName = "JV_OBJECT_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 246, Offset2 = 492)]
    [XmlElement("JV_OBJECT_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Object_Type
    { 
       get
       {
          return _Jv_Object_Type;
       }
       set
       {
          _Jv_Object_Type = value;
       }
    }
    private string _Jv_Object_Type;


    /// <summary>
    /// JIB/JIBE Class
    /// </summary>
 
    [RfcField(AbapName = "JV_JIB_CLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 250, Offset2 = 500)]
    [XmlElement("JV_JIB_CLASS", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jib_Class
    { 
       get
       {
          return _Jv_Jib_Class;
       }
       set
       {
          _Jv_Jib_Class = value;
       }
    }
    private string _Jv_Jib_Class;


    /// <summary>
    /// JIB/JIBE Subclass A
    /// </summary>
 
    [RfcField(AbapName = "JV_JIB_SUB_CLASS_A", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 253, Offset2 = 506)]
    [XmlElement("JV_JIB_SUB_CLASS_A", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jib_Sub_Class_A
    { 
       get
       {
          return _Jv_Jib_Sub_Class_A;
       }
       set
       {
          _Jv_Jib_Sub_Class_A = value;
       }
    }
    private string _Jv_Jib_Sub_Class_A;


    /// <summary>
    /// Deletion Indicator
    /// </summary>
 
    [RfcField(AbapName = "DELETION_FLAG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 258, Offset2 = 516)]
    [XmlElement("DELETION_FLAG", Form=XmlSchemaForm.Unqualified)]
    public string Deletion_Flag
    { 
       get
       {
          return _Deletion_Flag;
       }
       set
       {
          _Deletion_Flag = value;
       }
    }
    private string _Deletion_Flag;


    /// <summary>
    /// Object class, language-dependent
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 259, Offset2 = 518)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 264, Offset2 = 528)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Functional Area
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 268, Offset2 = 536)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;

  }

}
