
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI structure for network relationships
  /// </summary>
  [RfcStructure(AbapName ="BAPI_NETWORK_RELATION" , Length = 61, Length2 = 120)]
  [Serializable]
  public class BAPI_NETWORK_RELATION : SAPStructure
  {
   

    /// <summary>
    /// Order/Network number
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_PREDECESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 0, Offset2 = 0)]
    [XmlElement("NETWORK_PREDECESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Network_Predecessor
    { 
       get
       {
          return _Network_Predecessor;
       }
       set
       {
          _Network_Predecessor = value;
       }
    }
    private string _Network_Predecessor;


    /// <summary>
    /// Activity number in network and standard network
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_PREDECESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 12, Offset2 = 24)]
    [XmlElement("ACTIVITY_PREDECESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Activity_Predecessor
    { 
       get
       {
          return _Activity_Predecessor;
       }
       set
       {
          _Activity_Predecessor = value;
       }
    }
    private string _Activity_Predecessor;


    /// <summary>
    /// Order/Network number
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_SUCCESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 16, Offset2 = 32)]
    [XmlElement("NETWORK_SUCCESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Network_Successor
    { 
       get
       {
          return _Network_Successor;
       }
       set
       {
          _Network_Successor = value;
       }
    }
    private string _Network_Successor;


    /// <summary>
    /// Activity number in network and standard network
    /// </summary>
 
    [RfcField(AbapName = "ACTIVITY_SUCCESSOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 28, Offset2 = 56)]
    [XmlElement("ACTIVITY_SUCCESSOR", Form=XmlSchemaForm.Unqualified)]
    public string Activity_Successor
    { 
       get
       {
          return _Activity_Successor;
       }
       set
       {
          _Activity_Successor = value;
       }
    }
    private string _Activity_Successor;


    /// <summary>
    /// Type of Relationship (BOR 2002)
    /// </summary>
 
    [RfcField(AbapName = "RELATION_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 32, Offset2 = 64)]
    [XmlElement("RELATION_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Relation_Type
    { 
       get
       {
          return _Relation_Type;
       }
       set
       {
          _Relation_Type = value;
       }
    }
    private string _Relation_Type;


    /// <summary>
    /// Unit for the time interval between relationships
    /// </summary>
 
    [RfcField(AbapName = "DURATION_RELATION_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 34, Offset2 = 68)]
    [XmlElement("DURATION_RELATION_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Relation_Unit
    { 
       get
       {
          return _Duration_Relation_Unit;
       }
       set
       {
          _Duration_Relation_Unit = value;
       }
    }
    private string _Duration_Relation_Unit;


    /// <summary>
    /// Time interval between relationships
    /// </summary>
 
    [RfcField(AbapName = "DURATION_RELATION", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Decimals = 1, Offset = 37, Offset2 = 74)]
    [XmlElement("DURATION_RELATION", Form=XmlSchemaForm.Unqualified)]
    public Decimal Duration_Relation
    { 
       get
       {
          return _Duration_Relation;
       }
       set
       {
          _Duration_Relation = value;
       }
    }
    private Decimal _Duration_Relation;


    /// <summary>
    /// ISO code for unit of measurement
    /// </summary>
 
    [RfcField(AbapName = "DURATION_RELATION_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 40, Offset2 = 78)]
    [XmlElement("DURATION_RELATION_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Relation_Unit_Iso
    { 
       get
       {
          return _Duration_Relation_Unit_Iso;
       }
       set
       {
          _Duration_Relation_Unit_Iso = value;
       }
    }
    private string _Duration_Relation_Unit_Iso;


    /// <summary>
    /// Factory Calendar
    /// </summary>
 
    [RfcField(AbapName = "FACTORY_CALENDAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 43, Offset2 = 84)]
    [XmlElement("FACTORY_CALENDAR", Form=XmlSchemaForm.Unqualified)]
    public string Factory_Calendar
    { 
       get
       {
          return _Factory_Calendar;
       }
       set
       {
          _Factory_Calendar = value;
       }
    }
    private string _Factory_Calendar;


    /// <summary>
    /// % used to calc. time interval between predecessor/successor
    /// </summary>
 
    [RfcField(AbapName = "PERCENT_OF_SUC_PR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 45, Offset2 = 88)]
    [XmlElement("PERCENT_OF_SUC_PR", Form=XmlSchemaForm.Unqualified)]
    public string Percent_Of_Suc_Pr
    { 
       get
       {
          return _Percent_Of_Suc_Pr;
       }
       set
       {
          _Percent_Of_Suc_Pr = value;
       }
    }
    private string _Percent_Of_Suc_Pr;


    /// <summary>
    /// Key for defining time intervals in a relationship
    /// </summary>
 
    [RfcField(AbapName = "DURATION_KEY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 48, Offset2 = 94)]
    [XmlElement("DURATION_KEY", Form=XmlSchemaForm.Unqualified)]
    public string Duration_Key
    { 
       get
       {
          return _Duration_Key;
       }
       set
       {
          _Duration_Key = value;
       }
    }
    private string _Duration_Key;


    /// <summary>
    /// Work center
    /// </summary>
 
    [RfcField(AbapName = "WORK_CNTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 8, Length2 = 16, Offset = 49, Offset2 = 96)]
    [XmlElement("WORK_CNTR", Form=XmlSchemaForm.Unqualified)]
    public string Work_Cntr
    { 
       get
       {
          return _Work_Cntr;
       }
       set
       {
          _Work_Cntr = value;
       }
    }
    private string _Work_Cntr;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 57, Offset2 = 112)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;

  }

}
