
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{

  /// <summary>
  /// BAPI Structure Project Definition (Update Fields)
  /// </summary>
  [RfcStructure(AbapName ="BAPI_PROJECT_DEFINITION_UP" , Length = 40, Length2 = 80)]
  [Serializable]
  public class BAPI_PROJECT_DEFINITION_UP : SAPStructure
  {
   

    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_DEFINITION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("PROJECT_DEFINITION", Form=XmlSchemaForm.Unqualified)]
    public string Project_Definition
    { 
       get
       {
          return _Project_Definition;
       }
       set
       {
          _Project_Definition = value;
       }
    }
    private string _Project_Definition;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "DESCRIPTION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 1, Offset2 = 2)]
    [XmlElement("DESCRIPTION", Form=XmlSchemaForm.Unqualified)]
    public string Description
    { 
       get
       {
          return _Description;
       }
       set
       {
          _Description = value;
       }
    }
    private string _Description;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "MASK_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 2, Offset2 = 4)]
    [XmlElement("MASK_ID", Form=XmlSchemaForm.Unqualified)]
    public string Mask_Id
    { 
       get
       {
          return _Mask_Id;
       }
       set
       {
          _Mask_Id = value;
       }
    }
    private string _Mask_Id;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "RESPONSIBLE_NO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 3, Offset2 = 6)]
    [XmlElement("RESPONSIBLE_NO", Form=XmlSchemaForm.Unqualified)]
    public string Responsible_No
    { 
       get
       {
          return _Responsible_No;
       }
       set
       {
          _Responsible_No = value;
       }
    }
    private string _Responsible_No;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "APPLICANT_NO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 4, Offset2 = 8)]
    [XmlElement("APPLICANT_NO", Form=XmlSchemaForm.Unqualified)]
    public string Applicant_No
    { 
       get
       {
          return _Applicant_No;
       }
       set
       {
          _Applicant_No = value;
       }
    }
    private string _Applicant_No;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "COMP_CODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 5, Offset2 = 10)]
    [XmlElement("COMP_CODE", Form=XmlSchemaForm.Unqualified)]
    public string Comp_Code
    { 
       get
       {
          return _Comp_Code;
       }
       set
       {
          _Comp_Code = value;
       }
    }
    private string _Comp_Code;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "BUS_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 6, Offset2 = 12)]
    [XmlElement("BUS_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Bus_Area
    { 
       get
       {
          return _Bus_Area;
       }
       set
       {
          _Bus_Area = value;
       }
    }
    private string _Bus_Area;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "CONTROLLING_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 7, Offset2 = 14)]
    [XmlElement("CONTROLLING_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Controlling_Area
    { 
       get
       {
          return _Controlling_Area;
       }
       set
       {
          _Controlling_Area = value;
       }
    }
    private string _Controlling_Area;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROFIT_CTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 8, Offset2 = 16)]
    [XmlElement("PROFIT_CTR", Form=XmlSchemaForm.Unqualified)]
    public string Profit_Ctr
    { 
       get
       {
          return _Profit_Ctr;
       }
       set
       {
          _Profit_Ctr = value;
       }
    }
    private string _Profit_Ctr;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_CURRENCY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 9, Offset2 = 18)]
    [XmlElement("PROJECT_CURRENCY", Form=XmlSchemaForm.Unqualified)]
    public string Project_Currency
    { 
       get
       {
          return _Project_Currency;
       }
       set
       {
          _Project_Currency = value;
       }
    }
    private string _Project_Currency;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_CURRENCY_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 10, Offset2 = 20)]
    [XmlElement("PROJECT_CURRENCY_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Project_Currency_Iso
    { 
       get
       {
          return _Project_Currency_Iso;
       }
       set
       {
          _Project_Currency_Iso = value;
       }
    }
    private string _Project_Currency_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_ASSIGNMENT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 11, Offset2 = 22)]
    [XmlElement("NETWORK_ASSIGNMENT", Form=XmlSchemaForm.Unqualified)]
    public string Network_Assignment
    { 
       get
       {
          return _Network_Assignment;
       }
       set
       {
          _Network_Assignment = value;
       }
    }
    private string _Network_Assignment;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "START", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 12, Offset2 = 24)]
    [XmlElement("START", Form=XmlSchemaForm.Unqualified)]
    public string Start
    { 
       get
       {
          return _Start;
       }
       set
       {
          _Start = value;
       }
    }
    private string _Start;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FINISH", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 13, Offset2 = 26)]
    [XmlElement("FINISH", Form=XmlSchemaForm.Unqualified)]
    public string Finish
    { 
       get
       {
          return _Finish;
       }
       set
       {
          _Finish = value;
       }
    }
    private string _Finish;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 14, Offset2 = 28)]
    [XmlElement("PLANT", Form=XmlSchemaForm.Unqualified)]
    public string Plant
    { 
       get
       {
          return _Plant;
       }
       set
       {
          _Plant = value;
       }
    }
    private string _Plant;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "CALENDAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 15, Offset2 = 30)]
    [XmlElement("CALENDAR", Form=XmlSchemaForm.Unqualified)]
    public string Calendar
    { 
       get
       {
          return _Calendar;
       }
       set
       {
          _Calendar = value;
       }
    }
    private string _Calendar;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLAN_BASIC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 16, Offset2 = 32)]
    [XmlElement("PLAN_BASIC", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Basic
    { 
       get
       {
          return _Plan_Basic;
       }
       set
       {
          _Plan_Basic = value;
       }
    }
    private string _Plan_Basic;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLAN_FCST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 17, Offset2 = 34)]
    [XmlElement("PLAN_FCST", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Fcst
    { 
       get
       {
          return _Plan_Fcst;
       }
       set
       {
          _Plan_Fcst = value;
       }
    }
    private string _Plan_Fcst;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "TIME_UNIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 18, Offset2 = 36)]
    [XmlElement("TIME_UNIT", Form=XmlSchemaForm.Unqualified)]
    public string Time_Unit
    { 
       get
       {
          return _Time_Unit;
       }
       set
       {
          _Time_Unit = value;
       }
    }
    private string _Time_Unit;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "TIME_UNIT_ISO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 19, Offset2 = 38)]
    [XmlElement("TIME_UNIT_ISO", Form=XmlSchemaForm.Unqualified)]
    public string Time_Unit_Iso
    { 
       get
       {
          return _Time_Unit_Iso;
       }
       set
       {
          _Time_Unit_Iso = value;
       }
    }
    private string _Time_Unit_Iso;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "NETWORK_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 20, Offset2 = 40)]
    [XmlElement("NETWORK_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Network_Profile
    { 
       get
       {
          return _Network_Profile;
       }
       set
       {
          _Network_Profile = value;
       }
    }
    private string _Network_Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 21, Offset2 = 42)]
    [XmlElement("PROJECT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Project_Profile
    { 
       get
       {
          return _Project_Profile;
       }
       set
       {
          _Project_Profile = value;
       }
    }
    private string _Project_Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "BUDGET_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 22, Offset2 = 44)]
    [XmlElement("BUDGET_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Budget_Profile
    { 
       get
       {
          return _Budget_Profile;
       }
       set
       {
          _Budget_Profile = value;
       }
    }
    private string _Budget_Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PROJECT_STOCK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 23, Offset2 = 46)]
    [XmlElement("PROJECT_STOCK", Form=XmlSchemaForm.Unqualified)]
    public string Project_Stock
    { 
       get
       {
          return _Project_Stock;
       }
       set
       {
          _Project_Stock = value;
       }
    }
    private string _Project_Stock;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 24, Offset2 = 48)]
    [XmlElement("OBJECTCLASS", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass
    { 
       get
       {
          return _Objectclass;
       }
       set
       {
          _Objectclass = value;
       }
    }
    private string _Objectclass;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "STATISTICAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 25, Offset2 = 50)]
    [XmlElement("STATISTICAL", Form=XmlSchemaForm.Unqualified)]
    public string Statistical
    { 
       get
       {
          return _Statistical;
       }
       set
       {
          _Statistical = value;
       }
    }
    private string _Statistical;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "TAXJURCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 26, Offset2 = 52)]
    [XmlElement("TAXJURCODE", Form=XmlSchemaForm.Unqualified)]
    public string Taxjurcode
    { 
       get
       {
          return _Taxjurcode;
       }
       set
       {
          _Taxjurcode = value;
       }
    }
    private string _Taxjurcode;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "INT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 27, Offset2 = 54)]
    [XmlElement("INT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Int_Profile
    { 
       get
       {
          return _Int_Profile;
       }
       set
       {
          _Int_Profile = value;
       }
    }
    private string _Int_Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "WBS_SCHED_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 28, Offset2 = 56)]
    [XmlElement("WBS_SCHED_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Wbs_Sched_Profile
    { 
       get
       {
          return _Wbs_Sched_Profile;
       }
       set
       {
          _Wbs_Sched_Profile = value;
       }
    }
    private string _Wbs_Sched_Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "CSH_BDGT_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 29, Offset2 = 58)]
    [XmlElement("CSH_BDGT_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Csh_Bdgt_Profile
    { 
       get
       {
          return _Csh_Bdgt_Profile;
       }
       set
       {
          _Csh_Bdgt_Profile = value;
       }
    }
    private string _Csh_Bdgt_Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "PLAN_PROFILE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 30, Offset2 = 60)]
    [XmlElement("PLAN_PROFILE", Form=XmlSchemaForm.Unqualified)]
    public string Plan_Profile
    { 
       get
       {
          return _Plan_Profile;
       }
       set
       {
          _Plan_Profile = value;
       }
    }
    private string _Plan_Profile;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "JOINT_VENTURE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 31, Offset2 = 62)]
    [XmlElement("JOINT_VENTURE", Form=XmlSchemaForm.Unqualified)]
    public string Joint_Venture
    { 
       get
       {
          return _Joint_Venture;
       }
       set
       {
          _Joint_Venture = value;
       }
    }
    private string _Joint_Venture;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "RECOVERY_IND", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 32, Offset2 = 64)]
    [XmlElement("RECOVERY_IND", Form=XmlSchemaForm.Unqualified)]
    public string Recovery_Ind
    { 
       get
       {
          return _Recovery_Ind;
       }
       set
       {
          _Recovery_Ind = value;
       }
    }
    private string _Recovery_Ind;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "EQUITY_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 33, Offset2 = 66)]
    [XmlElement("EQUITY_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Equity_Type
    { 
       get
       {
          return _Equity_Type;
       }
       set
       {
          _Equity_Type = value;
       }
    }
    private string _Equity_Type;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "JV_OBJECT_TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 34, Offset2 = 68)]
    [XmlElement("JV_OBJECT_TYPE", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Object_Type
    { 
       get
       {
          return _Jv_Object_Type;
       }
       set
       {
          _Jv_Object_Type = value;
       }
    }
    private string _Jv_Object_Type;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "JV_JIB_CLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 35, Offset2 = 70)]
    [XmlElement("JV_JIB_CLASS", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jib_Class
    { 
       get
       {
          return _Jv_Jib_Class;
       }
       set
       {
          _Jv_Jib_Class = value;
       }
    }
    private string _Jv_Jib_Class;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "JV_JIB_SUB_CLASS_A", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 36, Offset2 = 72)]
    [XmlElement("JV_JIB_SUB_CLASS_A", Form=XmlSchemaForm.Unqualified)]
    public string Jv_Jib_Sub_Class_A
    { 
       get
       {
          return _Jv_Jib_Sub_Class_A;
       }
       set
       {
          _Jv_Jib_Sub_Class_A = value;
       }
    }
    private string _Jv_Jib_Sub_Class_A;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "OBJECTCLASS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 37, Offset2 = 74)]
    [XmlElement("OBJECTCLASS_EXT", Form=XmlSchemaForm.Unqualified)]
    public string Objectclass_Ext
    { 
       get
       {
          return _Objectclass_Ext;
       }
       set
       {
          _Objectclass_Ext = value;
       }
    }
    private string _Objectclass_Ext;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 38, Offset2 = 76)]
    [XmlElement("FUNC_AREA", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area
    { 
       get
       {
          return _Func_Area;
       }
       set
       {
          _Func_Area = value;
       }
    }
    private string _Func_Area;


    /// <summary>
    /// Updated information in related user data field
    /// </summary>
 
    [RfcField(AbapName = "FUNC_AREA_LONG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 39, Offset2 = 78)]
    [XmlElement("FUNC_AREA_LONG", Form=XmlSchemaForm.Unqualified)]
    public string Func_Area_Long
    { 
       get
       {
          return _Func_Area_Long;
       }
       set
       {
          _Func_Area_Long = value;
       }
    }
    private string _Func_Area_Long;

  }

}
