
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 8/29/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace CSAPData
{
  /// <summary>
  /// A typed collection of BAPIPAREX elements.
  /// </summary>
  [Serializable]
  public class BAPIPAREXTable : SAPTable 
  {
  
    /// <summary>
    /// Returns the element type BAPIPAREX.
    /// </summary>
    /// <returns>The type BAPIPAREX.</returns>
    public override Type GetElementType() 
    {
        return (typeof(BAPIPAREX));
    }

    /// <summary>
    /// Creates an empty new row of type BAPIPAREX.
    /// </summary>
    /// <returns>The newBAPIPAREX.</returns>
    public override object CreateNewRow()
    { 
        return new BAPIPAREX();
    }
     
    /// <summary>
    /// The indexer of the collection.
    /// </summary>
    public BAPIPAREX this[int index] 
    {
        get 
        {
            return ((BAPIPAREX)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    /// <summary>
    /// Adds a BAPIPAREX to the end of the collection.
    /// </summary>
    /// <param name="value">The BAPIPAREX to be added to the end of the collection.</param>
    /// <returns>The index of the newBAPIPAREX.</returns>
    public int Add(BAPIPAREX value) 
    {
        return List.Add(value);
    }
        
    /// <summary>
    /// Inserts a BAPIPAREX into the collection at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index at which value should be inserted.</param>
    /// <param name="value">The BAPIPAREX to insert.</param>
    public void Insert(int index, BAPIPAREX value) 
    {
        List.Insert(index, value);
    }
        
    /// <summary>
    /// Searches for the specified BAPIPAREX and returnes the zero-based index of the first occurrence in the collection.
    /// </summary>
    /// <param name="value">The BAPIPAREX to locate in the collection.</param>
    /// <returns>The index of the object found or -1.</returns>
    public int IndexOf(BAPIPAREX value) 
    {
        return List.IndexOf(value);
    }
        
    /// <summary>
    /// Determines wheter an element is in the collection.
    /// </summary>
    /// <param name="value">The BAPIPAREX to locate in the collection.</param>
    /// <returns>True if found; else false.</returns>
    public bool Contains(BAPIPAREX value) 
    {
        return List.Contains(value);
    }
        
    /// <summary>
    /// Removes the first occurrence of the specified BAPIPAREX from the collection.
    /// </summary>
    /// <param name="value">The BAPIPAREX to remove from the collection.</param>
    public void Remove(BAPIPAREX value) 
    {
        List.Remove(value);
    }

    /// <summary>
    /// Copies the contents of the BAPIPAREXTable to the specified one-dimensional array starting at the specified index in the target array.
    /// </summary>
    /// <param name="array">The one-dimensional destination array.</param>           
    /// <param name="index">The zero-based index in array at which copying begins.</param>           
    public void CopyTo(BAPIPAREX[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
